// @trace implements FR-014-001, FR-014-002, FR-014-007, FR-014-008, FR-014-011
import React,{useEffect,useRef,useState} from 'react';
import {Button,DataComponent} from '../../data-app-public.jsx';
import {Field} from '../dashboard/Forms.jsx';
import {request,scoped} from '../business/api.mjs';
import {useWriteAccess} from '../business/TeamAccess.jsx';
import './visual-studio.css';
const STAGES=['BRIEF','RESEARCH','STRATEGY','CONCEPT','COPY','ART_DIRECTION','QA','HUMAN_REVIEW','READY_FOR_CAMPAIGN'];
const LABELS={BRIEF:'Brief',RESEARCH:'Research',STRATEGY:'Strategy',CONCEPT:'Concept',COPY:'Copy',ART_DIRECTION:'Visual prompt',QA:'Creative QA',HUMAN_REVIEW:'Human approval',READY_FOR_CAMPAIGN:'พร้อมส่งต่อ',REVISION:'รอแก้ Brief',REJECTED:'ไม่อนุมัติ'};
const ASSIGNED={BRIEF:'Visual Marketing Lead',RESEARCH:'Audience Researcher',STRATEGY:'Creative Strategist',CONCEPT:'Creative Strategist',COPY:'Copywriter',ART_DIRECTION:'Art Director',QA:'Creative Reviewer',HUMAN_REVIEW:'Project owner',READY_FOR_CAMPAIGN:'Project owner',REVISION:'Project owner',REJECTED:'Project owner'};
const BRAND=[['identity','ชื่อ / อัตลักษณ์แบรนด์'],['positioning','จุดยืน'],['audience','กลุ่มเป้าหมายแบรนด์'],['tone_of_voice','น้ำเสียง'],['colors','สี',true],['typography','ตัวอักษร'],['visual_language','ภาษาภาพ'],['photography_style','สไตล์ภาพ'],['composition_rules','กฎการจัดองค์ประกอบ',true],['messaging_rules','กฎการสื่อสาร',true],['approved_claims','คำกล่าวอ้างที่ยืนยันแล้ว',true],['forbidden_claims','คำกล่าวอ้างที่ห้าม',true],['positive_examples','ตัวอย่างที่ดี',true],['negative_examples','ตัวอย่างที่ไม่ใช้',true]];
const BRIEF=[['objective','วัตถุประสงค์'],['product','สินค้า / บริการ'],['offer','ข้อเสนอ'],['audience','ผู้ชมเป้าหมาย'],['insight','Insight'],['message','ข้อความหลัก'],['proof_points','หลักฐานสนับสนุน',true],['channel','ช่องทาง'],['format','รูปแบบ'],['aspect_ratio','อัตราส่วนภาพ เช่น 1:1'],['cta','Call to action'],['tone','น้ำเสียงงานนี้'],['visual_direction','ทิศทางภาพ'],['mandatory_elements','สิ่งที่ต้องมี',true],['forbidden_elements','สิ่งที่ห้าม',true],['references','แหล่งอ้างอิง',true],['due_date','วันส่ง']];
const CHECKS=[['brand_consistency','ตรงกับแบรนด์'],['message_accuracy','ข้อความถูกต้อง'],['offer_accuracy','ข้อเสนอถูกต้อง'],['cta_clarity','CTA ชัดเจน'],['channel_suitability','เหมาะกับช่องทาง'],['policy_safety','ปลอดภัยตามนโยบาย'],['hallucinated_claims','ไม่มีคำกล่าวอ้างไร้หลักฐาน'],['duplicate_concepts','ไม่ซ้ำแนวคิดเดิม']];
const lines=value=>(value||'').split('\n').map(v=>v.trim()).filter(Boolean);
const fields=(defs,draft)=>Object.fromEntries(defs.map(([key,,array])=>[key,array?lines(draft[key]):draft[key]||null]));
const initialBrief={aspect_ratio:'1:1',format:'copy + visual prompt'};
export function VisualStudio(){
 const {viewer,canWrite,requestWrite}=useWriteAccess(),scope=viewer.kind+':'+(viewer.memberId||''),generation=useRef(0);
 const [dataScope,setDataScope]=useState(scope);
 const [business,setBusiness]=useState(null),[projects,setProjects]=useState([]),[board,setBoard]=useState(null),[team,setTeam]=useState(null),[selected,setSelected]=useState(''),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [brand,setBrand]=useState({}),[brandSourceRefs,setBrandSourceRefs]=useState(''),[brief,setBrief]=useState(initialBrief),[brandConfirmed,setBrandConfirmed]=useState(false),[strategyGate,setStrategyGate]=useState(false),[text,setText]=useState(''),[claims,setClaims]=useState(''),[assessment,setAssessment]=useState({}),[reason,setReason]=useState(''),[grant,setGrant]=useState(false);
 const [detailLoading,setDetailLoading]=useState(false),[revisionOpen,setRevisionOpen]=useState(false),[campaigns,setCampaigns]=useState([]),[campaign,setCampaign]=useState('');
 const route=(path,method='GET',body)=>scoped(business,'/visual-marketing'+path,method,body);
 async function boot(){const token=++generation.current;setLoading(true);setDataScope(scope);setError('');setDetail(null);setBoard(null);setProjects([]);setTeam(null);setSelected('');setBrand({});setBrandSourceRefs('');setBrief(initialBrief);setText('');setClaims('');setAssessment({});setGrant(false);setBrandConfirmed(false);setReason('');setCampaign('');setCampaigns([]);setBusy(false);
  try{const bootstrap=await request('/bootstrap'),b=bootstrap.business.id;const [p,board,team,state]=await Promise.all([scoped(b,'/projects'),scoped(b,'/visual-marketing/projects'),scoped(b,'/visual-marketing/team'),scoped(b,'/state')]);if(generation.current!==token)return;setBusiness(b);setProjects(p.projects);setBoard(board);setTeam(team);setCampaigns(state.campaigns||[]);}catch(e){if(generation.current===token)setError(e.message+' · '+(e.code||'เชื่อมต่อไม่สำเร็จ'));}finally{if(generation.current===token)setLoading(false);}}
 useEffect(()=>{boot();const changed=()=>boot();window.addEventListener('zuri-go-viewer-changed',changed);return()=>{generation.current++;window.removeEventListener('zuri-go-viewer-changed',changed);};},[scope]);
 async function loadProject(p,token=generation.current){if(!p)return;try{const d=await route('/projects/'+p);if(generation.current===token)setDetail(d);}catch(e){if(generation.current===token){setDetail(null);setError(e.message+' · '+(e.code||''));}}}
 async function choose(p){const token=++generation.current;setDetailLoading(true);setSelected(p);setDetail(null);setError('');setNotice('');setText('');setClaims('');setAssessment({});setReason('');setGrant(false);setRevisionOpen(false);setBrand({});setBrandSourceRefs('');setBrief(initialBrief);setBrandConfirmed(false);try{if(p){const d=await route('/projects/'+p);if(generation.current===token)setDetail(d);}}catch(e){if(generation.current===token&&e.code!=='NOT_FOUND')setError(e.message);}finally{if(generation.current===token)setDetailLoading(false);}}
 async function act(operation){if(!canWrite){requestWrite(null);return;}const token=generation.current;setBusy(true);setError('');setNotice('');try{await operation();if(token!==generation.current)return;const next=await route('/projects');if(token!==generation.current)return;setBoard(next);await loadProject(selected,token);if(token===generation.current){setNotice('บันทึกแล้ว');setText('');setClaims('');setGrant(false);}}catch(e){if(token===generation.current)setError(e.message+' · '+(e.code||''));}finally{if(token===generation.current)setBusy(false);}}
 const row=detail?.project,currentBrief=detail?.briefs.find(b=>b.id===row?.current_brief_id),bundle=detail?.artifacts.find(a=>a.kind==='BUNDLE'&&a.revision===row?.revision),qa=detail?.reviews.find(r=>r.artifact_id===bundle?.id),activeJob=detail?.jobs.find(j=>['queued','running'].includes(j.state));
 useEffect(()=>{if(!activeJob||!selected)return;const token=generation.current,timer=setInterval(()=>loadProject(selected,token),2000);return()=>clearInterval(timer);},[activeJob?.id,activeJob?.state,selected]);
 const meta=()=>({row_version:row.row_version,idempotency_key:crypto.randomUUID()}),post=(path,data)=>route(path,'POST',data);
 async function saveBrief(e){e.preventDefault();const refs=lines(brandSourceRefs);if(lines(brand.approved_claims).length&&!refs.length){setError('เพิ่มแหล่งอ้างอิงอย่างน้อยหนึ่งรายการสำหรับคำกล่าวอ้างที่ยืนยันแล้ว');return;}if(refs.length>20||refs.some(ref=>ref.length>2000)){setError('แหล่งอ้างอิงรองรับไม่เกิน 20 รายการ และไม่เกิน 2,000 ตัวอักษรต่อรายการ');return;}await act(async()=>{let target=row;if(!target)target=await post('/projects',{project_id:selected,idempotency_key:crypto.randomUUID(),strategy_approval_required:strategyGate});const bp=await post('/brand-profiles',{project_id:selected,idempotency_key:crypto.randomUUID(),profile:fields(BRAND,brand),source_refs:refs,confirmed:brandConfirmed});await post('/briefs',{project_id:selected,row_version:target.row_version,idempotency_key:crypto.randomUUID(),brief:{...fields(BRIEF,brief),project_id:selected,brand_profile_id:bp.id,campaign_id:campaign||null}});setRevisionOpen(false);});}
 function revise(){setRevisionOpen(true);setBrandConfirmed(false);const bp=detail.brands.find(b=>b.id===currentBrief?.brand_profile_id);setBrand(Object.fromEntries(BRAND.map(([k,,a])=>[k,a?(bp?.profile[k]||[]).join('\n'):bp?.profile[k]||''])));setBrandSourceRefs((bp?.source_refs||[]).join('\n'));setBrief(Object.fromEntries(BRIEF.map(([k,,a])=>[k,a?(currentBrief?.payload[k]||[]).join('\n'):currentBrief?.payload[k]||''])));setCampaign(currentBrief?.campaign_id||'');}
 function download(asset){act(async()=>{const result=await route(`/assets/${asset.id}/download`),url=URL.createObjectURL(new Blob([result.text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 const sourceRows=board?.projects||[];
 const recentRun=id=>detail?.runs.find(r=>r.agent_id===id),providerRun=detail?.provider_runs?.[0];
 if(dataScope!==scope)return <p role="status">กำลังเปิดข้อมูลสำหรับผู้ใช้ปัจจุบัน…</p>;
 return <article className="mc-app vm-studio" aria-busy={loading||busy}>
  <header className="vm-heading"><div><span className="mc-kicker">VISUAL MARKETING TEAM</span><h2>Visual Studio</h2><p>จาก Brief สู่ข้อความและ Visual prompt ที่ทีมตรวจและอนุมัติได้</p></div><Button onClick={boot} disabled={busy}>โหลดใหม่</Button></header>
  {error&&<p className="mc-errors" role="alert">{error}</p>}{notice&&<p className="mc-notice" role="status">{notice}</p>}{loading&&<p role="status">กำลังเปิด Studio…</p>}
  {!loading&&board&&<>
   {viewer.kind==='guest'?<section className="vm-panel"><h3>ผลงานสาธารณะที่อนุมัติแล้ว</h3>{board.public_outputs.length?board.public_outputs.map(a=><div key={a.artifact_id}><p>{a.payload.copy}</p><pre>{a.payload.visual_prompt}</pre></div>):<p>ยังไม่มีผลงานสาธารณะ</p>}<Button onClick={()=>requestWrite(null)}>เข้าสู่ระบบเพื่อเปิดงานของทีม</Button></section>:<>
    <div className="vm-toolbar"><Field label="Project เดิม" value={selected} options={[{value:'',label:'เลือก Project'},...projects.map(p=>({value:p.id,label:p.code+' · '+p.name}))]} onChange={choose} disabled={busy}/><span>{viewer.kind==='operator'?'Local operator':'Member'} · ข้อมูลบันทึกใน PostgreSQL</span></div>
    {!projects.length&&<p>เพิ่ม Project และเจ้าของใน Task Manager ก่อนเริ่มงาน</p>}
    <DataComponent id="visual-studio-board" title="Creative projects" kind="custom" queryId="zuri_go_workspace" sourceRows={sourceRows} displayRows={sourceRows}><div className="vm-board">{sourceRows.map(p=><button key={p.project_id} className={selected===p.project_id?'vm-selected':''} onClick={()=>choose(p.project_id)} disabled={busy}><strong>{p.name}</strong><span>{LABELS[p.stage]||p.stage} · revision {p.revision}</span><span>{p.campaign_name||"ไม่มี Campaign"} · {p.channel||"ยังไม่ระบุช่องทาง"}</span><span>{p.objective||"รอ Brief"}</span><span>ผู้รับขั้นตอน: {ASSIGNED[p.stage]||p.stage}</span><span>{p.stage==='READY_FOR_CAMPAIGN'?'อนุมัติแล้ว':'ยังไม่อนุมัติ revision นี้'} · Variants: ยังไม่เปิด</span><span>Owner / PIC: {p.owner_name||"—"} · ส่ง {p.due_date||"ยังไม่กำหนด"}</span><small>{(p.preview||"ยังไม่มีผลงาน").slice(0,120)}</small></button>)}{!sourceRows.length&&<p>เลือก Project แล้วสร้าง Brief แรกของทีม</p>}</div></DataComponent>{board.next_cursor&&<Button disabled={busy} onClick={()=>{const token=generation.current;route('/projects?cursor='+board.next_cursor).then(next=>{if(token===generation.current)setBoard(old=>({...next,projects:[...old.projects,...next.projects]}));}).catch(e=>{if(token===generation.current)setError(e.message);});}}>โหลด Project เพิ่ม</Button>}
    {row&&<ol className="vm-stages" aria-label="ขั้นตอนงาน">{STAGES.map(s=><li key={s} aria-current={row.stage===s?'step':undefined}>{LABELS[s]}</li>)}</ol>}
     {detailLoading&&<p role="status">กำลังเปิด Project…</p>}{selected&&!detailLoading&&(!row||!currentBrief||revisionOpen)&&<form className="vm-panel" onSubmit={saveBrief}><h3>{row?.revision?'แก้ Brief · สร้าง revision ใหม่':'เริ่ม Creative Brief'}</h3><p>ช่องรายการใช้หนึ่งรายการต่อบรรทัด · ผลงานรอบนี้เป็น copy + visual prompt ยังไม่ใช่ไฟล์ภาพ</p><h4>Brand context</h4><div className="mc-form-grid">{BRAND.map(([k,label,array])=><Field key={k} label={label} type={array?'textarea':'text'} value={brand[k]} required={k==='identity'} maxLength={4000} onChange={v=>setBrand(d=>({...d,[k]:v}))}/>)}</div><Field label="แหล่งอ้างอิงคำกล่าวอ้าง (หนึ่งรายการต่อบรรทัด)" type="textarea" value={brandSourceRefs} maxLength={40019} onChange={setBrandSourceRefs}/>{lines(brand.approved_claims).length>0&&<p role="note">คำกล่าวอ้างที่ยืนยันแล้วต้องมีแหล่งอ้างอิงอย่างน้อย 1 รายการ · สูงสุด 20 รายการ และ 2,000 ตัวอักษรต่อรายการ</p>}<label className="vm-check"><input type="checkbox" required checked={brandConfirmed} onChange={e=>setBrandConfirmed(e.target.checked)}/>ยืนยัน Brand context สำหรับงานนี้</label><h4>Structured Brief</h4><div className="mc-form-grid"><Field label="Campaign (ไม่บังคับ)" value={campaign} onChange={setCampaign} options={[{value:'',label:'ไม่เชื่อม Campaign'},...campaigns.map(c=>({value:c.id,label:c.name}))]}/>{BRIEF.map(([k,label,array])=><Field key={k} label={label} type={k==='due_date'?'date':array?'textarea':'text'} required={['objective','product','audience','message','channel','format','aspect_ratio','cta'].includes(k)} maxLength={4000} value={brief[k]} onChange={v=>setBrief(d=>({...d,[k]:v}))}/>)}</div>{!row&&<label className="vm-check"><input type="checkbox" checked={strategyGate} onChange={e=>setStrategyGate(e.target.checked)}/>ให้เจ้าของอนุมัติ Strategy ก่อนสร้าง Concept</label>}<Button type="submit" disabled={busy||!brandConfirmed}>บันทึก Brief</Button>{revisionOpen&&<Button type="button" onClick={()=>setRevisionOpen(false)}>ยกเลิก</Button>}</form>}
    {row&&currentBrief&&!revisionOpen&&<>
     <div className="vm-toolbar"><strong>revision {row.revision} · {LABELS[row.stage]||row.stage}</strong>{row.revision<3&&<Button disabled={busy||!!activeJob} onClick={revise}>แก้ Brief เป็น revision ใหม่</Button>}</div>
     <details className="vm-panel"><summary>Brief ที่ยืนยันแล้ว</summary><dl>{BRIEF.map(([k,label])=><div key={k}><dt>{label}</dt><dd>{Array.isArray(currentBrief.payload[k])?currentBrief.payload[k].join(' · '):currentBrief.payload[k]||'—'}</dd></div>)}</dl></details>
     {activeJob&&<section className="vm-panel" role="status"><strong>กำลังทำ {activeJob.stage}</strong><p>{activeJob.state} · attempt {activeJob.attempt} · ปิดหน้าจอแล้วกลับมาดูต่อได้</p><Button disabled={busy} onClick={()=>act(()=>post(`/jobs/${activeJob.id}/cancel`,{row_version:activeJob.row_version,idempotency_key:crypto.randomUUID()}))}>ยกเลิกงานโมเดล</Button></section>}
     {detail.jobs[0]?.state==='failed'&&<p role="alert">งานโมเดลหยุด: {detail.jobs[0].error_class} · ทำขั้นตอนนี้ด้วยตนเองหรือเริ่มงานใหม่</p>}
     {STAGES.slice(1,6).includes(row.stage)&&!activeJob&&<section className="vm-panel"><h3>{LABELS[row.stage]}</h3>{row.stage==='CONCEPT'&&row.strategy_approval_required&&!row.strategy_approved?<><p>รอเจ้าของ Project อนุมัติ Strategy</p>{detail.can_approve&&<Button disabled={busy} onClick={()=>act(()=>post(`/projects/${selected}/strategy-decision`,{...meta(),input_hash:currentBrief.input_hash,decision:'approve'}))}>อนุมัติ Strategy</Button>}</>:<><form onSubmit={e=>{e.preventDefault();act(()=>post(`/projects/${selected}/stages`,{...meta(),stage:row.stage,input_hash:currentBrief.input_hash,output:{text,claims:lines(claims)}}));}}><Field label="ผลงานขั้นตอนนี้" type="textarea" value={text} onChange={setText} required maxLength={4000}/><Field label="คำกล่าวอ้างที่ใช้ (ตรงกับหลักฐาน หนึ่งรายการต่อบรรทัด)" type="textarea" value={claims} onChange={setClaims} maxLength={4000}/><Button type="submit" disabled={busy}>บันทึกและไปขั้นต่อไป</Button></form><div className="vm-ai"><p>{team?.local_model_available?'ใช้โมเดลที่ operator ตั้งค่าในเครื่องเพื่อช่วยทำขั้นตอนที่เหลือ แล้วหยุดให้คนตรวจ QA':'ยังไม่ได้ตั้งค่าโมเดล · ทำงานด้วยตนเองได้ครบทุกขั้นตอน'}</p>{team?.local_model_available&&<><label className="vm-check"><input type="checkbox" checked={grant} onChange={e=>setGrant(e.target.checked)}/>อนุญาตส่ง Brief, Brand และผลงาน revision นี้ให้โมเดลในเครื่อง</label><Button disabled={busy||!grant} onClick={()=>act(()=>post(`/projects/${selected}/run`,{...meta(),input_hash:currentBrief.input_hash,authorize_local_model:true}))}>เริ่มงานโมเดล</Button></>}</div></>}</section>}
     <div className="vm-output-grid">{detail.artifacts.filter(a=>a.revision===row.revision&&!['BUNDLE','QA'].includes(a.kind)).reverse().map(a=><section className="vm-panel" key={a.id}><h3>{LABELS[a.kind]||a.kind}</h3><pre>{a.payload.text||a.payload.decision||(a.payload.status==='skipped_optional'?'ข้ามการสร้างภาพ · ส่งต่อ visual prompt':'')}</pre></section>)}</div>
     {bundle&&['QA','HUMAN_REVIEW'].includes(row.stage)&&<section className="vm-panel"><h3>Creative QA</h3><p>ตรวจ copy และ visual prompt · ยังไม่ได้ตรวจ readability / visual hierarchy ของภาพจริง</p><div className="vm-checks">{CHECKS.map(([k,label])=><label key={k} className="vm-check"><input type="checkbox" checked={!!assessment[k]} onChange={e=>setAssessment(a=>({...a,[k]:e.target.checked}))}/>{label}</label>)}</div><Button disabled={busy} onClick={()=>act(()=>post(`/artifacts/${bundle.id}/review`,{...meta(),assessment}))}>บันทึกผล QA</Button>{qa&&<><p>ผลล่าสุด: {qa.result.status}</p><ul>{qa.result.blockingIssues.map((f,i)=><li key={i}>{f.message}</li>)}</ul></>}</section>}
     {bundle&&row.stage==='HUMAN_REVIEW'&&<section className="vm-panel"><h3>Human approval</h3><p>การอนุมัติผูกกับผลงานและผล QA นี้ · เจ้าของ Project หรือ local operator เท่านั้น</p>{detail.can_approve?<><Field label="เหตุผล / สิ่งที่ให้แก้" type="textarea" value={reason} onChange={setReason} maxLength={4000}/><div className="vm-toolbar">{[['approve','อนุมัติพร้อมส่งต่อ'],['request_changes','ขอแก้ไข'],['reject','ไม่อนุมัติ']].map(([decision,label])=><Button key={decision} disabled={busy||decision!=='approve'&&!reason.trim()} onClick={()=>act(()=>post(`/artifacts/${bundle.id}/approve`,{...meta(),artifact_hash:bundle.content_hash,qa_revision:qa.id,decision,reason}))}>{label}</Button>)}</div></>:<p>รอเจ้าของ Project ตรวจอนุมัติ</p>}</section>}
     {!!detail.assets.length&&<section className="vm-panel"><h3>Assets · text/plain</h3>{detail.assets.filter(a=>a.artifact_id===bundle?.id).map(a=><Button key={a.id} disabled={busy} onClick={()=>download(a)}>ดาวน์โหลด Copy + Visual prompt</Button>)}<p>ไม่มีไฟล์ภาพที่สร้างขึ้นในรุ่นนี้</p></section>}
     {!!detail.decisions.length&&<section className="vm-panel"><h3>ประวัติการตัดสินใจ</h3>{detail.decisions.map(d=><p key={d.id}>{d.decision} · {d.actor_kind} · {new Date(d.created_at).toLocaleString('th-TH')} {d.reason}</p>)}</section>}
    </>}
   </>}
   <details className="vm-panel"><summary>ทีมและความสามารถ</summary><div className="vm-team">{team?.agents.map(a=><section key={a.id}><strong>{a.identity}</strong><p>{a.responsibility}</p><small>{a.available?'Manual / โมเดลเมื่อพร้อม':'ยังไม่เปิดใช้งาน'}</small><p>งานล่าสุด: {recentRun(a.id)?.stage||'—'} · {recentRun(a.id)?.status||'ยังไม่เริ่ม'}</p><small>{recentRun(a.id)?new Date(recentRun(a.id).started_at).toLocaleString('th-TH'):''}</small></section>)}</div></details>
   {detail&&<details className="vm-panel"><summary>ประวัติงานและการใช้โมเดล</summary>{detail.jobs.map(j=><p key={j.id}>{j.stage} · {j.state} · {j.error_class||'ไม่มีข้อผิดพลาดที่บันทึก'}</p>)}<p>Provider / model ล่าสุด: {providerRun?providerRun.provider+' / '+(providerRun.model||'ไม่ทราบ'):'ยังไม่มีการเรียกโมเดล'}</p><p>Tokens: {providerRun?.usage?JSON.stringify(providerRun.usage):'ไม่ทราบ'} · ค่าใช้จ่าย: {providerRun?.estimated_cost??'ไม่ทราบ'}</p><p>Variant: ยังไม่เปิดใช้งาน</p></details>}<Button disabled title="Phase E ยังไม่เปิดใช้งาน">สร้างตัวเลือก · ยังไม่เปิดใช้งาน</Button><p className="mc-note">Variants / A-B และ Performance learning ยังไม่เปิดใช้งาน · การอนุมัติผลงานไม่ใช่การเผยแพร่แคมเปญ</p>
  </>}
 </article>;
}
