import {useWriteAccess} from '../business/TeamAccess.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from '../../data-app-public.jsx';
import {Field} from '../dashboard/Forms.jsx';
import {createFungClient} from './fung-client.mjs';
import {MOSCOW,weekOf,hash,uid,addSource,adoptSource,saveReview,reviewHash,addBatch,commitBatch,isBatchStale,memberName} from './model.mjs';
import pairChart from '../assets/metrics-pair-chart_gen-04ac9b83.webp';
import {VisibilityFields} from './Visibility.jsx';
const stamp=ms=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;

export function Meetings({state,change,selectedId,onSelect,onTask,onOpenTask,week,notice,teams=null}){
  const {canWrite,requestWrite}=useWriteAccess();
  const client=useRef(null),[url,setUrl]=useState(''),[connected,setConnected]=useState(false),[capabilities,setCapabilities]=useState(null),[recordings,setRecordings]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState(null),[legacyConfirmed,setLegacyConfirmed]=useState(false),[connectionOpen,setConnectionOpen]=useState(false);
  const requestId=useRef(null);
  useEffect(()=>{if(!canWrite){disconnect();setConnectionOpen(false);}},[canWrite]);
  useEffect(()=>()=>client.current?.disconnect(),[]);
  function run(fn){return requestWrite(()=>runAction(fn));}
  async function runAction(fn){setBusy(true);setError('');try{return await fn();}catch(e){setError(e.message);return null;}finally{setBusy(false);}}
  async function connect(){await run(async()=>{client.current?.disconnect();setConnected(false);const legacyId=state.legacySourceInstanceId||uid();const next=createFungClient(url,{legacySourceInstanceId:legacyId});client.current=next;const result=await next.connect();if(client.current!==next)return;if(!state.legacySourceInstanceId)await change(s=>{s.legacySourceInstanceId=legacyId;});setRecordings(result.recordings);setCapabilities(result.capabilities);setConnected(true);setUrl('');setConnectionOpen(false);notice('เชื่อมต่อ FUNG สำเร็จ ตรวจสิทธิ์อ่าน recordings แล้ว');});}
  function disconnect(){client.current?.disconnect();client.current=null;setConnected(false);setCapabilities(null);setRecordings([]);setUrl('');setLegacyConfirmed(false);}
  async function importRecording(recording){return run(async()=>{if(!capabilities&&!legacyConfirmed)throw Error('ยืนยัน FUNG instance เดิมก่อนนำเข้า Legacy');const source=await client.current.snapshot(recording,capabilities);if(!source.segments.length)throw Error('ยังไม่มีข้อความถอดเสียง ไม่สร้างประชุม Ready จาก transcript ว่าง');const id=await change(s=>addSource(s,source,{...recording,title:recording.projectName||recording.id,originalFilename:job?.recordingId===recording.id?job.name:null}),'นำเข้าต้นฉบับแล้ว');onSelect(id);});}
  const meeting=state.meetings.find(m=>m.id===selectedId),source=state.sources.find(s=>s.id===meeting?.sourceId),review=state.reviews.find(r=>r.id===meeting?.reviewId),batches=state.batches.filter(b=>b.meetingId===meeting?.id).slice().reverse();
  async function extract(){await run(async()=>{if(!connected||!client.current)throw Error('เชื่อมต่อ FUNG ก่อนสร้างร่างด้วยโมเดล');if(!capabilities?.actionDraft?.available)throw Error(capabilities?.actionDraft?.reasonCode||'FUNG ยังไม่พร้อมสร้างร่างด้วยโมเดล local');if(!review||review.sourceId!==source.id)throw Error('บันทึกฉบับตรวจแล้วก่อนสร้างร่าง');const key=`${review.id}:${review.reviewHash}`;if(requestId.current?.key!==key)requestId.current={key,id:uid()};const reply=await client.current.draft({requestId:requestId.current.id,sourceInstanceId:source.sourceInstanceId,projectId:source.projectId,recordingId:source.recordingId,expectedSourceHash:source.contentHash,reviewRevisionId:review.id,reviewHash:review.reviewHash,reviewedSegments:review.segments.map(s=>({segmentId:s.segmentId,startMs:s.startMs,endMs:s.endMs,text:s.text,speakerLabel:s.speakerLabel??null})),locale:'th-TH',meetingStartedAt:meeting.meetingStartedAt,timezone:'Asia/Bangkok'});await change(s=>addBatch(s,meeting.id,reply),'ได้ร่างงานแล้ว กรุณาตรวจหลักฐานและผู้รับผิดชอบ');});}
  async function commit(batch,choices){if(!client.current||!connected)throw Error('เชื่อมต่อ FUNG เพื่อตรวจฉบับต้นทางก่อนสร้างงาน');const latest=await client.current.snapshot({id:source.recordingId,projectId:source.projectId},capabilities);if(latest.contentHash!==source.contentHash){await change(s=>addSource(s,latest,meeting));throw Error('ต้นทางเปลี่ยนแล้ว ตรวจฉบับใหม่ก่อนสร้างงาน');}const payloadHash=await hash(choices);return change(s=>commitBatch(s,batch.id,choices,payloadHash),'สร้างและมอบหมายงานในเครื่องแล้ว');}
  return <section className="mt-meetings"><div className="mt-connection-summary"><div><span className={`mt-connection-dot ${connected?'on':''}`}/><strong>{connected?'FUNG connected':'ยังไม่เชื่อม FUNG'}</strong><small>{connected?(capabilities?.actionDraft?.available?'โมเดล local พร้อม':'อ่าน transcript ได้ · โมเดลยังไม่พร้อม'):'สร้างงานเองและตรวจประชุมที่นำเข้าไว้ได้'}</small></div><Button onClick={()=>requestWrite(()=>setConnectionOpen(!connectionOpen))}>ตั้งค่าการเชื่อมต่อ</Button></div>
    {connectionOpen&&<div className="mt-connection"><h3>FUNG บนเครื่องนี้</h3><p>เปิด FUNG › Settings › Runtime แล้วคัดลอก Connect URL มาวาง เมื่อปิดหรือรีสตาร์ท FUNG ให้เชื่อมใหม่</p><div className="mt-quick"><Field label="FUNG Connect URL" type="password" autoComplete="off" value={url} disabled={!canWrite} onChange={setUrl} placeholder="http://127.0.0.1:PORT/#TOKEN"/><Button className="mc-primary" disabled={busy||!url} onClick={connect}>เชื่อมต่อ</Button>{connected&&<Button disabled={busy} onClick={disconnect}>ยกเลิกการเชื่อมต่อ</Button>}</div><p className="mc-note">Token ใช้เฉพาะการเปิดหน้านี้ ไม่รวมใน Backup</p></div>}
    {error&&<p role="alert" className="mc-errors">{error}</p>}
    {connected&&<div className="mt-intake"><div className="mt-intake-title"><h3>รับเสียงและประชุมจาก FUNG</h3><Button disabled={busy} onClick={()=>run(async()=>setRecordings(await client.current.recordings()))}>อัปเดตรายการ</Button></div><label className="mt-upload">＋ อัปโหลดเสียงไป FUNG<input disabled={busy} type="file" accept="audio/*,video/mp4,video/webm,.wav,.flac,.m4a,.mov" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)run(async()=>{const receipt=await client.current.upload(file);setJob({...receipt,status:'accepted',name:file.name});});}}/></label>{job&&<div className="mt-job"><span>{job.name} · {job.status}{job.errorMessage&&` · ${job.errorMessage}`}</span><Button disabled={busy} onClick={()=>run(async()=>{const value=await client.current.job(job.jobId);setJob(old=>({...old,...value,jobId:old.jobId}));setRecordings(await client.current.recordings());})}>ตรวจสถานะถอดเสียง</Button></div>}
      {!capabilities&&<label className="mt-check"><input type="checkbox" checked={legacyConfirmed} onChange={e=>setLegacyConfirmed(e.target.checked)}/> ยืนยันว่าเป็น FUNG เครื่องเดิม · Legacy transcript ไม่มี native revision และยังใช้ AI drafting ไม่ได้</label>}
      <div className="mt-recordings">{recordings.map(r=><div key={r.id}><span><strong>{r.projectName||r.id}</strong><small>{r.status||'สถานะไม่ระบุ'} · {stamp(r.durationMs||0)} · {r.id.slice(0,8)}</small></span><Button disabled={busy||(!capabilities&&!legacyConfirmed)} onClick={()=>importRecording(r)}>นำเข้า / ตรวจฉบับใหม่</Button></div>)}{!recordings.length&&<p className="mc-note">ยังไม่มี recording ให้เลือก</p>}</div></div>}
    <div className="mt-meeting-layout"><aside className="mt-meeting-list"><h3>ประชุมที่นำเข้า <span>{state.meetings.length}</span></h3>{state.meetings.map(m=><button className={selectedId===m.id?'selected':''} key={m.id} onClick={()=>onSelect(m.id)}><strong>{m.title}</strong><small>{m.meetingStartedAt?new Date(m.meetingStartedAt).toLocaleString('th-TH'):'ยังไม่ระบุวันประชุม'}</small><small>{state.tasks.filter(t=>t.sourceRefs.some(r=>r.meetingId===m.id)).length} งานที่สร้าง / ผูกแล้ว</small></button>)}{!state.meetings.length&&<p>เชื่อม FUNG แล้วเลือกประชุม หรือเริ่มจากเพิ่มงานเอง</p>}<img className="mt-meeting-mascot" src={pairChart} alt="Zuri และ น้องวางใจ ตรวจข้อความประชุมและงานที่ต้องไปต่อ"/></aside>
      <div className="mt-meeting-detail">{meeting&&source?<><MeetingMeta key={meeting.id} meeting={meeting} teams={teams} members={state.members} onSave={input=>change(s=>{const m=s.meetings.find(v=>v.id===meeting.id);if(!input.title.trim())throw Error('กรอกชื่อประชุม');m.title=input.title.trim();m.meetingStartedAt=input.date?`${input.date}:00+07:00`:null;if(input.access){for(const k of ['visibility','teamId','participantIds','organizerId'])m[k]=input.access[k]??null;if(input.access.visibilityReason?.trim())m.visibilityReason=input.access.visibilityReason.trim();else delete m.visibilityReason;}})}/>
        {meeting.latestSourceId!==meeting.sourceId&&<div className="mt-source-change"><strong>มีต้นฉบับใหม่จาก FUNG</strong><details><summary>เทียบข้อความก่อนเลือกใช้</summary><div className="mt-source-diff"><pre>{source.segments.map(s=>s.text).join('\n')}</pre><pre>{state.sources.find(s=>s.id===meeting.latestSourceId)?.segments.map(s=>s.text).join('\n')}</pre></div></details><Button onClick={()=>run(()=>change(s=>adoptSource(s,meeting.id,meeting.latestSourceId),'เปลี่ยนต้นฉบับแล้ว ฉบับตรวจเก่ายังอยู่ในประวัติ'))}>ใช้ฉบับใหม่และตรวจอีกครั้ง</Button></div>}
        <ReviewEditor key={`${meeting.id}:${source.id}:${meeting.reviewId||''}`} meeting={meeting} source={source} review={review?.sourceId===source.id?review:null} state={state} change={change} client={connected?client.current:null} canExtract={!!capabilities?.actionDraft?.available&&meeting.latestSourceId===meeting.sourceId} busy={busy} onExtract={extract} onNewExtract={()=>{requestId.current=null;extract();}} onTask={onTask} notice={notice}/>
        {batches.length>0&&<section className="mt-action-review"><h3>Action Review</h3>{batches.map((batch,i)=><ActionBatch key={batch.id} batch={batch} state={state} week={week} onCommit={choices=>commit(batch,choices)} onOpenTask={onOpenTask} collapsed={i>0}/>)}</section>}
      </>:<div className="mt-meeting-empty"><h3>จากบทสนทนา → งานที่ทำต่อได้</h3><ol><li>นำเข้าเสียงหรือเลือกประชุมจาก FUNG</li><li>ตรวจข้อความและชื่อผู้พูด</li><li>ตรวจร่างงาน เลือก R และสัปดาห์</li><li>สร้างงานแล้วติดตามใน Weekly To-do</li></ol><Button onClick={()=>requestWrite(()=>setConnectionOpen(true))}>เชื่อมต่อ FUNG เพื่อเริ่ม</Button></div>}</div>
    </div>
  </section>;
}
function MeetingMeta({meeting,onSave,teams,members}){const {canWrite,requestWrite}=useWriteAccess();const [access,setAccess]=useState({visibility:meeting.visibility,teamId:meeting.teamId,participantIds:meeting.participantIds||[],organizerId:meeting.organizerId});const [title,setTitle]=useState(meeting.title),[date,setDate]=useState(meeting.meetingStartedAt?new Date(meeting.meetingStartedAt).toLocaleString('sv-SE',{timeZone:'Asia/Bangkok'}).slice(0,16).replace(' ','T'):''),[error,setError]=useState('');return <div>{!canWrite&&<Button onClick={()=>requestWrite(null)}>แก้ไขข้อมูลประชุม</Button>}<fieldset className="mt-access-fields" disabled={!canWrite}><form className="mt-meeting-meta" onSubmit={async e=>{e.preventDefault();try{await onSave({title,date,access:teams?{...access,organizerId:access.organizerId&&access.participantIds.includes(access.organizerId)?access.organizerId:access.participantIds[0]||null}:null});setError('');}catch(e){setError(e.message);}}}><Field label="ชื่อประชุม" value={title} required onChange={setTitle}/><Field label="วันเวลาประชุม · Bangkok" type="datetime-local" value={date} onChange={setDate}/>{teams&&<VisibilityFields value={access} original={meeting} onChange={patch=>setAccess(a=>({...a,...patch}))} teams={teams} members={members} peopleKey="participantIds" peopleLabel="ผู้เข้าร่วม (เห็นประชุมนี้)" hint="ประชุมลับเห็นได้เฉพาะผู้เข้าร่วม · ผู้เข้าร่วมคนแรกเป็นผู้จัดประชุมถ้ายังไม่ได้กำหนด · transcript ของประชุมลับยังบันทึกบนคลาวด์ไม่ได้"/>}<Button type="submit">บันทึกข้อมูลประชุม</Button>{error&&<p role="alert">{error}</p>}</form></fieldset></div>;}

function ReviewEditor({meeting,source,review,state,change,client,canExtract,busy,onExtract,onNewExtract,onTask,notice}){
  const {canWrite,requestWrite}=useWriteAccess();
  const working=meeting.workingCopy?.sourceId===source.id?meeting.workingCopy.segments:null;
  const [segments,setSegments]=useState(()=>structuredClone(working||review?.segments||source.segments)),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[audio,setAudio]=useState(null),[channel,setChannel]=useState(meeting.channels?.[0]||'');
  const player=useRef(null),editSeq=useRef(0),changeRef=useRef(change);changeRef.current=change;
  const changed=!review||JSON.stringify(segments.map(s=>[s.text,s.speakerLabel]))!==JSON.stringify(review.segments.map(s=>[s.text,s.speakerLabel]));
  useEffect(()=>{if(!dirty)return;const seq=editSeq.current;const timer=setTimeout(async()=>{try{await changeRef.current(s=>{const m=s.meetings.find(m=>m.id===meeting.id);if(m.sourceId!==source.id)throw Error('ต้นฉบับเปลี่ยนแล้ว');m.workingCopy={sourceId:source.id,segments:structuredClone(segments),updatedAt:new Date().toISOString()};},'บันทึกร่างข้อความแล้ว ยังไม่ได้ยืนยันฉบับตรวจ');if(seq===editSeq.current)setDirty(false);}catch(e){setError(e.message);}},650);return()=>clearTimeout(timer);},[segments,dirty,meeting.id,source.id]);
  useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio);},[audio]);
  function edit(index,key,value){editSeq.current++;setSegments(v=>v.map((s,i)=>i===index?{...s,[key]:value}:s));setDirty(true);}
  async function save(){setSaving(true);setError('');try{const id=uid(),fingerprint=await reviewHash(id,segments);await change(s=>{const result=saveReview(s,{id,sourceId:source.id,segments,reviewHash:fingerprint});delete s.meetings.find(m=>m.id===meeting.id).workingCopy;return result;},'บันทึกฉบับตรวจแล้ว');}catch(e){setError(e.message);}finally{setSaving(false);}}
  async function loadAudio(){setError('');try{const blob=await client.audio(source.recordingId,channel);setAudio(URL.createObjectURL(blob));}catch(e){setError(e.message);}}
  function manual(seg){if(!review||changed)return;onTask({title:'',description:seg.text,sourceKind:'manual-from-meeting',sourceRefs:[{meetingId:meeting.id,sourceId:source.id,reviewRevisionId:review.id,evidence:[{segmentId:seg.segmentId,startMs:seg.startMs,endMs:seg.endMs,quote:seg.text,reviewRevisionId:review.id}]}],status:'planned',statusConfirmed:true,consultedIds:[],informedIds:[]});}
  return <section className="mt-transcript"><div className="mt-transcript-heading"><div><h3>Transcript Review</h3><small>{source.sourceMode==='native'?'Native revision':'Legacy · ไม่ยืนยัน native revisions'} · {source.segments.length} ช่วงข้อความ · coverage {source.coverage?.status||'unknown'}</small></div><Button className="mc-primary" disabled={saving||!segments.length} onClick={()=>requestWrite(save)}>{saving?'กำลังบันทึก…':'บันทึกฉบับตรวจแล้ว'}</Button></div>
    {error&&<p className="mc-errors" role="alert">{error}</p>}<p className="mc-note">{dirty?'กำลังบันทึกร่าง…':changed?'ร่างข้อความยังไม่ใช่ฉบับตรวจแล้ว':'กำลังดูฉบับตรวจแล้ว'} · ชื่อผู้พูดไม่ได้แปลว่าเป็น R</p>
    <div className="mt-audio"><Field label="ช่องเสียง" value={channel} options={[{value:'',label:'เลือกอัตโนมัติจาก FUNG'},...(meeting.channels||[]).map(value=>({value,label:value}))]} onChange={v=>{setChannel(v);setAudio(null);}}/><Button disabled={!client} onClick={loadAudio}>โหลดเสียงอ้างอิง</Button>{audio&&<audio ref={player} controls src={audio}/>}{!client&&<small>เชื่อม FUNG เพื่อเล่นเสียง</small>}</div>
    {!canWrite&&<Button onClick={()=>requestWrite(null)}>แก้ไข Transcript</Button>}<div className="mt-segments">{segments.map((seg,i)=><div className="mt-segment" key={seg.segmentId}><div className="mt-segment-top"><button disabled={!audio} onClick={()=>{if(player.current){player.current.currentTime=seg.startMs/1000;player.current.play().catch(()=>{});}}}>{stamp(seg.startMs)}–{stamp(seg.endMs)}</button><Field label={`ผู้พูดช่วง ${i+1}`} value={seg.speakerLabel} onChange={v=>edit(i,'speakerLabel',v)} disabled={saving||!canWrite}/></div><Field label={`ข้อความช่วง ${i+1}`} type="textarea" value={seg.text} onChange={v=>edit(i,'text',v)} disabled={saving||!canWrite}/><details><summary>ต้นฉบับ / สิ่งที่แก้</summary><p className="mt-raw">{source.segments[i]?.text}</p>{seg.text!==source.segments[i]?.text&&<p><b>ฉบับแก้:</b> {seg.text}</p>}</details><Button disabled={!review||changed||!seg.text.trim()} onClick={()=>manual(seg)}>สร้างงานเองจากช่วงนี้</Button></div>)}</div>
    <div className="mt-draft-actions"><Button className="mc-primary" disabled={busy||saving||dirty||changed||!canExtract} onClick={onExtract}>สร้างร่างงานด้วย FUNG</Button><Button disabled={busy||changed||!canExtract} onClick={onNewExtract}>วิเคราะห์ใหม่</Button>{!canExtract&&<small>โมเดล local / adapter ยังไม่พร้อม หรือมีต้นฉบับใหม่ · ใช้สร้างงานเองจากข้อความที่ตรวจแล้วได้</small>}</div>
    <details className="mt-history"><summary>ประวัติฉบับตรวจ ({state.reviews.filter(r=>r.meetingId===meeting.id).length})</summary>{state.reviews.filter(r=>r.meetingId===meeting.id).slice().reverse().map(r=><details key={r.id}><summary>{new Date(r.reviewedAt).toLocaleString('th-TH')} · {r.id.slice(0,8)}</summary><pre>{r.segments.map(s=>s.text).join('\n')}</pre></details>)}</details>
  </section>;
}

function ActionBatch({batch,state,week,onCommit,onOpenTask,collapsed}){
  const {requestWrite}=useWriteAccess();
  const previous=state.tasks.filter(t=>t.sourceRefs.some(r=>r.meetingId===batch.meetingId)),receipt=state.receipts.find(r=>r.batchId===batch.id),stale=isBatchStale(state,batch);
  const [choices,setChoices]=useState(()=>batch.items.map(item=>({proposalId:item.proposalId,mode:item.kind==='task'&&!previous.length?'create':'skip',title:item.title,description:null,responsibleId:'',accountableId:'',dueDate:item.suggestedDueDate||'',week,priority:null,taskId:'',taskVersion:null}))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const update=(i,key,value)=>requestWrite(()=>setChoices(v=>v.map((c,j)=>j===i?{...c,[key]:value,...(key==='taskId'?{taskVersion:state.tasks.find(t=>t.id===value)?.version??null}:{})}:c)));
  async function submit(){setBusy(true);setError('');try{await onCommit(choices);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <details className="mt-batch" open={!collapsed}><summary>{new Date(batch.generatedAt).toLocaleString('th-TH')} · {batch.items.length} รายการ · {receipt?'สร้างงานแล้ว':stale?'Stale · ต้องตรวจใหม่':'ร่างรอคุณตรวจ'}</summary>{receipt?<div className="mt-created">{receipt.taskIds.map(id=><Button key={id} onClick={()=>onOpenTask(id)}>{state.tasks.find(t=>t.id===id)?.title||id} ↗</Button>)}</div>:<>
    {error&&<p role="alert" className="mc-errors">{error}</p>}{previous.length>0&&<p className="mt-warning">ประชุมนี้มี {previous.length} งานแล้ว ตรวจรายการเดิมและเลือก ผูก / อัปเดต / สร้างใหม่ ทีละรายการเพื่อกันงานซ้ำ</p>}
    {batch.items.map((item,i)=><div key={item.proposalId} className="mt-proposal"><div className="mt-proposal-heading"><span>{item.kind==='task'?'งาน':item.kind==='decision'?'การตัดสินใจ':'คำถามค้าง'}</span><Field label={`จัดการร่าง ${i+1}`} value={choices[i].mode} disabled={stale||busy} options={[{value:'skip',label:'ไม่สร้าง'},{value:'create',label:'สร้างงานใหม่'},{value:'link',label:'ผูกกับงานเดิม'},{value:'update',label:'อัปเดตงานเดิม'}]} onChange={v=>update(i,'mode',v)}/></div><h4>{item.title}</h4>{item.evidence.map((e,j)=><blockquote key={j}>{e.quote}<small>{stamp(e.startMs)}–{stamp(e.endMs)}</small></blockquote>)}
      <p className="mc-note">{item.suggestedResponsibleLabel?`ชื่อที่เสนอ: ${item.suggestedResponsibleLabel} · `:''}{item.suggestedDueText?`วันส่งที่กล่าวถึง: ${item.suggestedDueText} · `:''}{item.unresolvedFields?.length?`รอยืนยัน: ${item.unresolvedFields.join(', ')}`:''}</p>
      {choices[i].mode!=='skip'&&<div className="mc-form-grid">{['link','update'].includes(choices[i].mode)&&<Field label={`งานเดิมของร่าง ${i+1}`} value={choices[i].taskId} options={[{value:'',label:'เลือกงานเดิม'},...state.tasks.map(t=>({value:t.id,label:`${t.title} · ${memberName(state,t.responsibleId)}`}))]} onChange={v=>update(i,'taskId',v)} wide/>}{choices[i].mode!=='link'&&<><Field label={`ชื่องานร่าง ${i+1}`} value={choices[i].title} onChange={v=>update(i,'title',v)} wide/><Field label={`รายละเอียดร่าง ${i+1}`} type="textarea" value={choices[i].description} onChange={v=>update(i,'description',v)} hint="กรอกภายหลังได้" wide/><Field label={`R ของร่าง ${i+1}`} value={choices[i].responsibleId} options={[{value:'',label:'เลือกผู้รับผิดชอบ'},...state.members.filter(m=>m.status==='active').map(m=>({value:m.id,label:`${m.displayName} · ${m.id.slice(0,4)}`}))]} onChange={v=>update(i,'responsibleId',v)}/><Field label={`A ของร่าง ${i+1}`} value={choices[i].accountableId} options={[{value:'',label:'รอยืนยัน'},...state.members.filter(m=>m.status==='active').map(m=>({value:m.id,label:m.displayName}))]} onChange={v=>update(i,'accountableId',v)}/><Field label={`วันส่งร่าง ${i+1}`} type="date" value={choices[i].dueDate} onChange={v=>update(i,'dueDate',v)}/></>}<Field label={`สัปดาห์ร่าง ${i+1}`} type="date" value={choices[i].week} onChange={v=>update(i,'week',weekOf(v))}/><Field label={`MoSCoW ร่าง ${i+1}`} value={choices[i].priority||''} options={[{value:'',label:'ยังไม่จัดลำดับ'},...Object.entries(MOSCOW).map(([value,label])=>({value,label}))]} onChange={v=>update(i,'priority',v||null)}/></div>}
    </div>)}<Button className="mc-primary" disabled={busy||stale||!choices.some(c=>c.mode!=='skip')} onClick={()=>requestWrite(submit)}>{busy?'กำลังตรวจและบันทึก…':`สร้างและมอบหมาย ${choices.filter(c=>c.mode!=='skip').length} งาน`}</Button><p className="mc-note">บันทึกผู้รับผิดชอบในเครื่องนี้ ไม่ส่งข้อความถึงทีม</p>
  </>}</details>;
}
