import {useWriteAccess} from '../business/TeamAccess.jsx';
import {ZuriGoLogo} from '../shared/ZuriGoLogo.jsx';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Button,SegmentedControl,useDataApp,useDashboardTabs} from '../../data-app-public.jsx';
import {Field,Modal} from '../dashboard/Forms.jsx';
import {download} from '../dashboard/Views.jsx';
import {createWorkspace,restoreWorkspace} from '../shared/model.mjs';
import {MOSCOW,STATUSES,today,weekOf,addDays,saveMember,saveTask,weeklyRows,weeklySummary,memberName,validateState} from './model.mjs';
import {openRepository,recoverRestore,restoreBoth} from './repository.mjs';
import {TaskForm,MemberForm} from './TaskForms.jsx';
import {Meetings} from './Meetings.jsx';
import seed from './seed.json';
import {BusinessWorkspace} from '../business/BusinessWorkspace.jsx';
import {modeKey,openServerRepository,scoped} from '../business/api.mjs';
import pairClipboard from '../assets/metrics-pair-clipboard_gen-80d72fb8.webp';
import pairAnalysis from '../assets/metrics-pair-analysis_gen-d190a201.webp';
import './meeting.css';

const TABS=[{id:'overview',label:'Overview'},{id:'campaigns',label:'Campaigns'},{id:'content',label:'Content'},{id:'goals',label:'Goals'},{id:'campaign-overview',label:'Campaign detail'},{id:'performance',label:'Performance'},{id:'plan',label:'Plan & Gates'},{id:'work',label:'Workboard'},{id:'review',label:'Review & Decisions'},{id:'meeting-task-manager',label:'Meeting & Task Manager'}];
const VIEWS=[{value:'weekly',label:'Weekly To-do'},{value:'meetings',label:'Meetings'},{value:'tasks',label:'Tasks / RACI'},{value:'members',label:'Members'}];
const dateLabel=value=>value?new Date(`${value}T12:00:00`).toLocaleDateString('th-TH',{day:'numeric',month:'short'}):'ยังไม่กำหนด';
function Priority({value}){return <span className={`mt-priority ${value||'unset'}`}>{MOSCOW[value]||'ยังไม่จัดลำดับ'}</span>;}

export function MeetingWorkspace({CampaignContent,cloudBusinessId=null}){
  const shell=useDataApp(),{activeTabId}=useDashboardTabs(TABS),inMeeting=activeTabId==='meeting-task-manager';
  const campaignKey=`zuri-mission-control:${shell.snapshot.id}:v1`;
  const [serverBusinessId,setServerBusinessId]=useState(()=>cloudBusinessId||localStorage.getItem(modeKey(shell.snapshot.id)));
  const repo=useMemo(()=>serverBusinessId?openServerRepository(serverBusinessId):openRepository(shell.snapshot.id,seed),[serverBusinessId,shell.snapshot.id]),repoRef=useRef(repo),pendingCampaign=useRef(new URLSearchParams(location.search).get('campaign'));repoRef.current=repo;
  const inBusiness=['overview','campaigns','content','goals'].includes(activeTabId);
  const [campaignWorkspace,setCampaignWorkspace]=useState(()=>{try{const raw=localStorage.getItem(campaignKey);return raw?restoreWorkspace(JSON.parse(raw)):createWorkspace();}catch{return createWorkspace();}});
  const [state,setState]=useState(null),[storageError,setStorageError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[restore,setRestore]=useState(null),[restoreError,setRestoreError]=useState(''),[epoch,setEpoch]=useState(0);
  const [view,setView]=useState('weekly'),[week,setWeek]=useState(weekOf(today())),[layout,setLayout]=useState('kanban'),[filter,setFilter]=useState('all'),[owner,setOwner]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState(false),[modal,setModalState]=useState(null),[selectedMeeting,setSelectedMeeting]=useState(null);
  const {canWrite,requestWrite}=useWriteAccess(),writeAllowed=useRef(canWrite);writeAllowed.current=canWrite;
  const setModal=value=>!value||value.task?.id||value.member?.id?setModalState(value):requestWrite(()=>setModalState(value));
  const input=useRef(null);
  async function load(){try{const value=await repo.read();if(repo!==repoRef.current)return;if(repo.server){const next=repo.campaign();setCampaignWorkspace(old=>({...next,selected:pendingCampaign.current||old.selected||next.selected}));pendingCampaign.current=null;}setState(old=>!old||value.revision>=old.revision?value:old);setStorageError('');}catch(e){setStorageError(e.message);}}
  async function boot(){try{await repo.init();if(!repo.server&&await recoverRestore(repo,campaignKey)){setCampaignWorkspace(restoreWorkspace(JSON.parse(localStorage.getItem(campaignKey))));setEpoch(v=>v+1);setNotice('กู้คืนชุดข้อมูลที่ค้างจนเสร็จแล้ว');}await load();}catch(e){setStorageError(e.message);}}
  useEffect(()=>{setState(null);boot();const unsubscribe=repo.subscribe(load);return()=>{unsubscribe();repo.close();};},[repo]);
  useEffect(()=>{if(serverBusinessId&&!inBusiness)load();},[activeTabId]);
  async function activateServer(id){localStorage.setItem(modeKey(shell.snapshot.id),id);if(serverBusinessId===id){await load();setEpoch(v=>v+1);}else{setServerBusinessId(id);setEpoch(v=>v+1);}}
  async function openCampaign(id,local=false,business=serverBusinessId){if(local&&cloudBusinessId)return;if(local){localStorage.removeItem(modeKey(shell.snapshot.id));setServerBusinessId(null);try{const raw=localStorage.getItem(campaignKey);setCampaignWorkspace(raw?restoreWorkspace(JSON.parse(raw)):createWorkspace());}catch{}setEpoch(v=>v+1);}else if(business){pendingCampaign.current=id;await activateServer(business);}shell.exploreDashboard('campaign-overview');if(id){const url=new URL(location.href);url.searchParams.set('campaign',id);history.replaceState(null,'',url);}}
  async function saveCampaignWorkspace(next){const saved=await scoped(serverBusinessId,'/workspace','PUT',{version:next.serverVersion,campaignWorkspace:next});const result={...saved.campaignWorkspace,serverVersion:saved.version,selected:saved.campaignWorkspace.campaigns.some(c=>c.id===next.selected)?next.selected:saved.campaignWorkspace.selected};setCampaignWorkspace(result);setState(saved.meetingTaskManager);return result;}
  async function change(fn,message='บันทึกงานแล้ว'){if(!writeAllowed.current){requestWrite(null);throw Error('กรุณาเข้าสู่ระบบก่อนแก้ไข');}setBusy(true);try{const result=await repo.mutate(fn);setState(result.state);setNotice(message);return result.result;}finally{setBusy(false);}}
  function openTask(task){setModal({kind:'task',task});}
  function openSource(id){setModal(null);setSelectedMeeting(id);setView('meetings');shell.exploreDashboard('meeting-task-manager');}
  function backup(){if(!state){download(`campaign-backup-${today()}.json`,campaignWorkspace);return;}const clean=structuredClone(state);delete clean.restoreJournal;download(`mission-control-backup-${today()}.json`,{schemaVersion:2,appId:shell.snapshot.id,exportedAt:new Date().toISOString(),campaignWorkspace,meetingTaskManager:clean});}
  async function importBackup(file){if(!file)return;if(repo.server){setNotice('PostgreSQL เก็บข้อมูลร่วมในเครื่องแล้ว การ Restore ทับชุดปัจจุบันยังไม่รองรับ ใช้ Backup เพื่อเก็บสำเนา');return;}setRestoreError('');try{if(file.size>25*1024*1024)throw Error('Backup ต้องไม่เกิน 25 MB');const value=JSON.parse(await file.text());if(value.schemaVersion===2){if(value.appId!==shell.snapshot.id)throw Error('Backup เป็นของแอปอื่น');if(value.meetingTaskManager?.restoreJournal)throw Error('ไม่รับ backup ที่มี restore journal ค้าง');setRestore({campaign:restoreWorkspace(value.campaignWorkspace),domain:validateState(value.meetingTaskManager)});}else setRestore({campaign:restoreWorkspace(value),domain:null});}catch(e){setNotice(`นำเข้าไม่ได้: ${e.message}`);}finally{if(input.current)input.current.value='';}}
  async function confirmRestore(){setBusy(true);setRestoreError('');try{backup();if(restore.domain)await restoreBoth(repo,campaignKey,restore.domain,restore.campaign);else localStorage.setItem(campaignKey,JSON.stringify(restore.campaign));setCampaignWorkspace(restore.campaign);setEpoch(v=>v+1);await load();setRestore(null);setModal(null);setNotice('Restore สำเร็จ เก็บ backup ชุดก่อนหน้าแล้ว');}catch(e){setRestoreError(e.message);}finally{setBusy(false);}}
  const allRows=state?weeklyRows(state,week):[],summary=weeklySummary(allRows);
  let rows=allRows.filter(t=>(filter==='all'||(filter==='unset'?!t.priority:t.priority===filter))&&(owner==='all'||t.responsibleId===owner)&&(!search||`${t.title} ${t.description||''}`.toLowerCase().includes(search.toLowerCase())));
  if(sort)rows=rows.slice().sort((a,b)=>(['must','should','could',null,'wont'].indexOf(a.priority))-(['must','should','could',null,'wont'].indexOf(b.priority)));
  function status(task,status){if(status===task.status)return;requestWrite(()=>change(s=>saveTask(s,{id:task.id,version:task.version,status,statusConfirmed:true})).catch(e=>setModal({kind:'task',task,error:e.message})));}
  function card(task){return <div key={task.id} className="mt-task" draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('application/x-zuri-task',task.id);e.dataTransfer.effectAllowed='move';}}><button className="mt-task-open" onClick={()=>openTask(task)}><div className="mt-card-top"><Priority value={task.priority}/><span>{task.seedTaskId||task.id.slice(0,6)}</span></div><h3>{task.title}</h3><p>{task.description||task.deliverable||'เพิ่มรายละเอียดภายหลังได้'}</p><div className="mt-assignee"><span className="mt-avatar">{memberName(state,task.responsibleId).slice(0,1)}</span><span>{memberName(state,task.responsibleId)}<small>A · {memberName(state,task.accountableId)}</small></span><span>{task.dueDate?dateLabel(task.dueDate):''}</span></div>{!task.statusConfirmed&&<small className="mt-warning">สถานะรอยืนยัน</small>}{task.blocker&&<p className="mt-warning">ติดขัด: {task.blocker}</p>}</button><footer><span>{task.sourceKind==='meeting'?'FUNG':task.sourceKind==='weekly-plan'?'Weekly plan':'Manual'}</span><label><span className="mc-sr-only">สถานะ {task.title}</span><select aria-label={`สถานะ ${task.title}`} disabled={busy} value={task.status} onChange={e=>status(task,e.target.value)}>{Object.entries(STATUSES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></footer></div>;}
  const linked=state?.tasks.filter(t=>t.campaignId===campaignWorkspace.selected)||[];
  return <div className="mt-shell"><nav className="mt-domain" aria-label="เมนูเว็บไซต์"><ZuriGoLogo compact/><Button className={!inMeeting?'mt-domain-selected':''} aria-current={!inMeeting?'page':undefined} onClick={()=>shell.exploreDashboard('overview')}>ภาพรวมธุรกิจ</Button><Button className={inMeeting?'mt-domain-selected':''} aria-current={inMeeting?'page':undefined} onClick={()=>shell.exploreDashboard('meeting-task-manager')}>Meeting & Task Manager</Button><a href="/metrics/#overview">ความรู้ Metrics</a><a href="/metrics/#metrics-graph">Graph View</a></nav>
    {inBusiness?<BusinessWorkspace cloud={!!cloudBusinessId} view={activeTabId} legacyCampaigns={campaignWorkspace} legacyDomain={state} onActivateServer={activateServer} onOpenCampaign={openCampaign} onOpenMeeting={()=>shell.exploreDashboard('meeting-task-manager')}/>:!inMeeting?(serverBusinessId&&!state?<article className="zg-app"><p role={storageError?'alert':'status'}>{storageError||'กำลังเปิดแคมเปญจาก PostgreSQL…'}</p>{storageError&&<Button onClick={boot}>ลองโหลดใหม่</Button>}</article>:!campaignWorkspace.campaigns.length?<article className="zg-app"><h2>ยังไม่มีแคมเปญ</h2><p>เพิ่มแคมเปญจากภาพรวมธุรกิจก่อนเริ่มวัดผล</p><Button onClick={()=>shell.exploreDashboard('campaigns')}>ไปหน้าแคมเปญ</Button><img src={pairAnalysis} width="180" alt="Zuri และน้องวางใจ"/></article>:<CampaignContent key={epoch+':'+serverBusinessId} view={activeTabId==='campaign-overview'?'overview':activeTabId} serverBusinessId={serverBusinessId} onSaveWorkspace={saveCampaignWorkspace} initialWorkspace={campaignWorkspace} onWorkspaceChange={setCampaignWorkspace} onBackup={backup} onImport={importBackup} linkedTasks={linked.length?<section className="mt-linked"><h3>งานที่เชื่อมจาก Meeting & Task Manager</h3>{linked.map(t=><button key={t.id} onClick={()=>{shell.exploreDashboard('meeting-task-manager');setView('tasks');openTask(t);}}>{t.title}<span>{memberName(state,t.responsibleId)} · {STATUSES[t.status]} ↗</span></button>)}</section>:null}/>):<article className="mc-app mt-app" data-reviewed-rows>
      <div className="mt-heading"><div><span className="mc-kicker">MEETING & TASK MANAGER</span><h2>คุยให้ชัด แล้วไปต่อให้เป็นงาน</h2><p>งานของทีม · {cloudBusinessId?'บันทึกใน PostgreSQL':'บันทึกในเครื่องนี้'}</p></div><div className="mt-heading-actions"><Button onClick={()=>{setView('meetings');setSelectedMeeting(null);}}>นำเข้างานจากประชุม</Button><Button className="mc-primary" onClick={()=>openTask(null)} disabled={!state||!!storageError}>＋ เพิ่มงาน</Button></div></div>
      <SegmentedControl value={view} options={VIEWS} onChange={setView}/>
      {storageError&&<div className="mc-errors" role="alert">{storageError}<Button onClick={boot}>ลองเปิดข้อมูลอีกครั้ง</Button></div>}
      {notice&&<div className="mc-notice" role="status">{notice}<button aria-label="ปิดข้อความ" onClick={()=>setNotice('')}>×</button></div>}
      {!state&&!storageError&&<p role="status">กำลังเปิดข้อมูลในเครื่อง…</p>}
      {state&&(view==='weekly'||view==='tasks')&&<>
        <div className="mt-week-bar"><div className="mt-week-title"><Button aria-label="สัปดาห์ก่อน" onClick={()=>setWeek(addDays(week,-7))}>←</Button><div><strong>{dateLabel(week)} – {dateLabel(addDays(week,6))}</strong><small>จันทร์–อาทิตย์ · {week.slice(0,4)}</small></div><Button aria-label="สัปดาห์ถัดไป" onClick={()=>setWeek(addDays(week,7))}>→</Button></div><Field label="เลือกสัปดาห์" type="date" value={week} onChange={v=>v&&setWeek(weekOf(v))}/><SegmentedControl value={layout} options={[{value:'kanban',label:'Kanban'},{value:'list',label:'List'},{value:'raci',label:'RACI'}]} onChange={setLayout}/></div>
        <div className="mt-overview"><div className="mt-totals"><div><span>งานในแผนสัปดาห์นี้</span><strong>{summary.total}<small> งาน</small></strong></div><div><span>เลือกทำ · M / S / C</span><strong>{summary.planned}<small> งาน</small></strong></div><div><span>เสร็จในกลุ่มที่เลือกทำ</span><strong>{summary.done}<small> / {summary.planned}</small></strong><small>{summary.percent===null?'ยังไม่จัดแผน / สถานะรอยืนยัน':`${summary.percent}%`}</small></div><div><span>รอจัดลำดับ / ไม่ทำรอบนี้</span><strong>{summary.unknown}<small> / {summary.deferred}</small></strong></div></div><aside className="mt-companion"><img src={pairClipboard} alt="Zuri และ น้องวางใจ ช่วยวางแผนงานรายสัปดาห์"/><p>เริ่มจากชื่อและคนรับผิดชอบ<br/><b>รายละเอียดค่อยเติมได้</b></p></aside></div>
        <div className="mt-filters"><Field label="ค้นหางาน" value={search} onChange={setSearch}/><Field label="กรอง MoSCoW" value={filter} options={[{value:'all',label:'ทุก priority'},{value:'unset',label:'ยังไม่จัดลำดับ'},...Object.entries(MOSCOW).map(([value,label])=>({value,label}))]} onChange={setFilter}/><Field label="กรอง R" value={owner} options={[{value:'all',label:'ทุกคน'},...state.members.map(m=>({value:m.id,label:m.displayName}))]} onChange={setOwner}/><label className="mt-check"><input type="checkbox" checked={sort} onChange={e=>setSort(e.target.checked)}/> เรียงตาม MoSCoW</label><Button onClick={()=>{setFilter('all');setOwner('all');setSearch('');setSort(false);}}>ล้างตัวกรอง</Button></div>
        {layout==='kanban'?<div className="mt-board">{Object.entries(STATUSES).filter(([key])=>key!=='blocked'||rows.some(t=>t.status==='blocked'&&t.priority!=='wont')).map(([key,label])=><section key={key} className={`mt-lane ${key}`} aria-label={label} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=state.tasks.find(t=>t.id===e.dataTransfer.getData('application/x-zuri-task'));if(t&&membershipForDrop(state,t.id,week))status(t,key);}}><header><h3>{label}</h3><span>{rows.filter(t=>t.status===key&&t.priority!=='wont').length}</span></header>{rows.filter(t=>t.status===key&&t.priority!=='wont').map(card)}{!rows.some(t=>t.status===key&&t.priority!=='wont')&&<p className="mt-empty-lane">ยังไม่มีงานในช่องนี้</p>}</section>)}</div>:<div className="mt-table-wrap"><table className="mt-table"><thead><tr><th>งาน</th><th>MoSCoW</th><th>R</th><th>A</th>{layout==='raci'?<><th>C</th><th>I</th></>:<><th>สถานะ</th><th>วันส่ง</th></>}</tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><button onClick={()=>openTask(t)}>{t.title}</button></td><td><Priority value={t.priority}/></td><td>{memberName(state,t.responsibleId)}</td><td>{memberName(state,t.accountableId)}{t.accountableId&&!t.accountableConfirmed?' · รอยืนยัน':''}</td>{layout==='raci'?<><td>{t.consultedIds.map(id=>memberName(state,id)).join(', ')||'—'}{t.raciProposed?' (เสนอ)':''}</td><td>{t.informedIds.map(id=>memberName(state,id)).join(', ')||'—'}{t.raciProposed?' (เสนอ)':''}</td></>:<><td>{STATUSES[t.status]}{!t.statusConfirmed?' · รอยืนยัน':''}</td><td>{dateLabel(t.dueDate)}</td></>}</tr>)}</tbody></table>{!rows.length&&<p className="mc-note">ไม่มีงานตรงสัปดาห์หรือตัวกรองที่เลือก</p>}</div>}
        {layout==='kanban'&&rows.some(t=>t.priority==='wont')&&<section className="mt-deferred"><h3>ไม่ทำในรอบนี้ · {rows.filter(t=>t.priority==='wont').length}</h3><div className="mt-card-grid">{rows.filter(t=>t.priority==='wont').map(card)}</div></section>}
        {view==='tasks'&&<section className="mt-backlog"><h3>งานทั้งหมด / Backlog · {state.tasks.length}</h3><p className="mc-note">เปิดงานเพื่อเพิ่มเข้าสัปดาห์ที่เลือก โดยเก็บประวัติรอบก่อน</p><div className="mt-all-tasks">{state.tasks.filter(t=>!search||t.title.toLowerCase().includes(search.toLowerCase())).map(t=><button key={t.id} onClick={()=>openTask(t)}><strong>{t.title}</strong><span>{memberName(state,t.responsibleId)} · {state.weeks.some(w=>w.entries.some(e=>e.taskId===t.id))?'อยู่ในแผนแล้ว':'ยังไม่กำหนดรอบ'}</span></button>)}</div></section>}
      </>}
      {state&&view==='members'&&<><div className="mt-member-head"><div><h3>ทีมของคุณ <span>{state.members.length} Members</span></h3><p>ชื่อเดียวก็เริ่มมอบหมายได้ รายละเอียดเติมภายหลัง</p></div><Button className="mc-primary" onClick={()=>setModal({kind:'member'})}>＋ ลงทะเบียน Member</Button></div><div className="mt-member-grid">{state.members.map(m=><button className={`mt-member ${m.status}`} key={m.id} onClick={()=>setModal({kind:'member',member:m})}><span className="mt-avatar">{m.displayName.slice(0,1)}</span><h3>{m.displayName}</h3><small>{m.pid||'PID จะกำหนดเมื่อบันทึกใน PostgreSQL'}</small><p>{[m.position,m.team].filter(Boolean).join(' · ')||'เพิ่มทีมและตำแหน่งได้'}</p><small>{m.email||m.phone||'รายละเอียดติดต่อยังว่าง'}</small><footer><span>{m.status==='active'?'Active':'Inactive'}</span><span>{state.tasks.filter(t=>t.responsibleId===m.id).length} งาน · {m.id.slice(0,4)} ↗</span></footer></button>)}</div><aside className="mt-companion wide"><img src={pairAnalysis} alt="Zuri และ น้องวางใจ ช่วยจัดผู้รับผิดชอบ"/><p><b>R ลงมือทำ · A ตรวจรับ</b><br/>C ให้คำปรึกษา · I รับทราบ<br/>บันทึกรายชื่อในเครื่อง ยังไม่มีการส่งข้อความหาทีม</p></aside></>}
      {state&&view==='meetings'&&<Meetings state={state} change={change} selectedId={selectedMeeting} onSelect={setSelectedMeeting} onTask={openTask} onOpenTask={id=>openTask(state.tasks.find(t=>t.id===id))} week={week} notice={setNotice}/>}
      <footer className="mc-footer"><span>{serverBusinessId?(cloudBusinessId?'PostgreSQL ของทีม · บันทึกบนคลาวด์':'PostgreSQL ในเครื่อง · สำรองข้อมูลก่อนย้ายเครื่อง'):'Browser workspace · สำรองข้อมูลก่อนย้าย browser/เครื่อง'}</span><div><Button onClick={backup}>{serverBusinessId?'Backup แคมเปญและงาน':'Backup JSON'}</Button><Button onClick={()=>requestWrite(()=>input.current?.click())}>Restore backup</Button></div></footer>
    </article>}
    <input ref={input} hidden type="file" accept=".json,application/json" onChange={e=>importBackup(e.target.files?.[0])}/>
    {!inMeeting&&notice&&<p className="mc-notice" role="status">{notice}</p>}
    {restore&&<Modal title="ตรวจ backup ก่อนกู้คืน" onClose={()=>setRestore(null)} wide={false}>{restoreError&&<p className="mc-errors" role="alert">{restoreError}</p>}<p>{restore.campaign.campaigns.length} แคมเปญ · {restore.domain?`${restore.domain.tasks.length} งาน / ${restore.domain.members.length} Members`:'Backup v1: เปลี่ยนเฉพาะแคมเปญ งานและ Members ในโดเมนใหม่คงเดิม'}</p><p>จะแทนที่ข้อมูลใน browser นี้ และดาวน์โหลดชุดปัจจุบันเก็บไว้ก่อน</p><div className="mc-form-actions"><Button onClick={()=>setRestore(null)}>ยกเลิก</Button><Button className="mc-primary" disabled={busy} onClick={confirmRestore}>ยืนยันกู้คืน</Button></div></Modal>}
    {state&&modal?.kind==='member'&&<MemberForm member={modal.member} members={state.members} onSave={input=>change(s=>saveMember(s,input))} onClose={()=>setModal(null)}/>}
    {state&&modal?.kind==='task'&&<TaskForm businessId={serverBusinessId} initialError={modal.error} task={modal.task} week={modal.task?.id&&!membershipForDrop(state,modal.task.id,week)?'':week} entry={membershipForDrop(state,modal.task?.id,week)} state={state} campaigns={campaignWorkspace.campaigns} onSave={(input,plan)=>change(s=>saveTask(s,input,plan))} onMember={input=>change(s=>saveMember(s,input))} onClose={()=>setModal(null)} onSource={openSource}/>}
  </div>;
}
function membershipForDrop(s,id,week){return s.weeks.find(w=>w.weekStart===week)?.entries.find(e=>e.taskId===id);}
