import {TeamAccess,useWriteAccess} from '../business/TeamAccess.jsx';
import {ZuriGoLogo} from '../shared/ZuriGoLogo.jsx';
import React, {useEffect,useRef,useState} from 'react';
import {Button,Chart,DataComponent,DataTable,DateRangePicker,Dropdown,SegmentedControl,SortableItem,SortableRegion,useDataApp} from '../../data-app-public.jsx';
import {OFFERS,OBJECTIVES,PRIMARY,today,uid,dayDiff,plusDays,createWorkspace,createCampaign,restoreWorkspace,measure,evaluate,trend,stockAt,capacity,alertList,evidenceSnapshot,settingsSnapshot,targetBand} from '../shared/model.mjs';
import {SettingsForm,RecordForm,DecisionForm,ReleaseForm,RECORD_LABELS,Field,Modal,fmt,pct,offerName} from './Forms.jsx';
import {dateLabel,STATUS,DEFINITIONS,metricFormat,download,Badge,Empty,Panel,Companion,Metric,PhaseRail,Evidence,PeriodComparison,Ledger,Forecast,NewCampaign,Acknowledge,ReviewEditor,SnapshotDetail,MetricDetail} from './Views.jsx';
import './example.css';
import {MeetingWorkspace} from '../meeting/MeetingWorkspace.jsx';

export function DashboardContent(){return <TeamAccess>{session=><MeetingWorkspace CampaignContent={CampaignContent} cloudBusinessId={session.storage==='postgresql-cloud'?session.businessId:null}/>}</TeamAccess>;}
function CampaignContent({view='overview',initialWorkspace,onWorkspaceChange,onBackup,onImport,linkedTasks,serverBusinessId,onSaveWorkspace}){
  const shell=useDataApp(),{canWrite,requestWrite}=useWriteAccess();
  const setModal=value=>!value||['history','decisionDetail','reviewDetail'].includes(value.kind)?setModalState(value):requestWrite(()=>setModalState(value));
  const storageKey=`zuri-mission-control:${shell.snapshot.id}:v1`,initial=useRef(null);
  if(!initial.current){try{const raw=serverBusinessId?null:localStorage.getItem(storageKey);initial.current={workspace:raw?restoreWorkspace(JSON.parse(raw)):(initialWorkspace||createWorkspace()),error:''};}catch(e){initial.current={workspace:initialWorkspace||createWorkspace(),error:`อ่านข้อมูลที่บันทึกไว้ไม่ได้: ${e.message}`};}}
  const [ws,setWs]=useState(initial.current.workspace),[storageError,setStorageError]=useState(initial.current.error),[notice,setNotice]=useState(''),[asOf,setAsOf]=useState(today()),[modal,setModalState]=useState(null),[detail,setDetail]=useState(null);
  const [offer,setOffer]=useState('all'),[channel,setChannel]=useState('all'),[range,setRange]=useState(''),[ledger,setLedger]=useState('ads'),[taskStatus,setTaskStatus]=useState('all');
  const importInput=useRef(null);
  useEffect(()=>{if(serverBusinessId&&initialWorkspace?.serverVersion!=null)setWs(initialWorkspace);},[initialWorkspace,serverBusinessId]);
  useEffect(()=>{if(serverBusinessId||storageError)return;try{localStorage.setItem(storageKey,JSON.stringify(ws));}catch{setStorageError('บันทึกใน browser ไม่สำเร็จ กรุณาดาวน์โหลด backup ก่อนปิดหน้า');}},[ws,storageKey,storageError]);
  useEffect(()=>{if(!serverBusinessId)onWorkspaceChange?.(ws);},[ws,onWorkspaceChange]);
  useEffect(()=>{const change=e=>{if(!serverBusinessId&&e.key===storageKey)setStorageError('ข้อมูลถูกเปลี่ยนจากอีกหน้าต่าง กรุณา backup หน้านี้แล้วโหลดใหม่ก่อนแก้ต่อ');};window.addEventListener('storage',change);return()=>window.removeEventListener('storage',change);},[storageKey]);
  const c=ws.campaigns.find(c=>c.id===ws.selected)||ws.campaigns[0],g=evaluate(c,asOf),m=g.all;
  const [rangeStart,rangeEnd]=range.split('..'),scope={from:rangeStart||c.start,to:rangeEnd||asOf,offer,channel},pm=measure(c,scope),alerts=alertList(c,asOf);
  const changeCampaign=id=>{setWs(w=>({...w,selected:id}));setOffer('all');setChannel('all');setRange('');setDetail(null);};
  async function persist(next,message){if(storageError)return;try{const saved=serverBusinessId?await onSaveWorkspace(next):next;setWs(saved);setNotice(message||(serverBusinessId?'บันทึกใน PostgreSQL แล้ว':'บันทึกใน browser นี้แล้ว'));return true;}catch(e){setStorageError(e.message);return false;}}
  function update(fn,message){return requestWrite(()=>persist({...ws,campaigns:ws.campaigns.map(x=>x.id===c.id?fn(structuredClone(x)):x)},message));}
  const openRecord=(type,record)=>setModal({kind:'record',type,record});
  const openMetric=(key,metricScope={from:c.start,to:asOf})=>setDetail({key,scope:metricScope});
  const doBackup=()=>onBackup();
  async function importBackup(file){await onImport(file);if(importInput.current)importInput.current.value='';}
  const scopedExport=()=>{const cohortOrders=c.orders.filter(o=>pm.leads.some(l=>l.id===o.leadId)&&o.date<=scope.to);download(`campaign-view-${scope.to}.json`,{campaignId:c.id,campaign:c.name,scope,thresholdVersion:c.version,source:'Manual records entered in this browser; provisional',metrics:pm,cohortLinkedOrders:cohortOrders});setNotice('Export ใช้ช่วงวันที่ / offer / channel ของ Performance ที่แสดง');};
  const cards=[['units','Net fulfilled units'],['revenue','Net revenue'],['spend','Media spend'],['contribution','Contribution after media'],['ctr','Link CTR'],['cvr','Mature Lead-to-Sale'],['cpl','CPL'],['cpo','CPO'],['mediaCAC','Media CAC'],['aov','AOV · purchase cohort'],['upo','Units per order'],['sla','Response SLA']];
  const chartSpec={type:'line',x:'date',y:'actual',fields:['actual','Low','Mid','High'],colors:{actual:'var(--chart-1)',Low:'var(--chart-8)',Mid:'var(--chart-5)',High:'var(--chart-3)'},legend:{labels:{actual:'Actual',Low:'Low plan',Mid:'Mid plan',High:'High plan'}},valueDecimals:1,showLegend:true,startAtZero:true,showXAxisLabel:false,showYAxisLabel:false};
  const chartRows=trend(c,{to:asOf});
  const supportKey=c.objective==='awareness'?'ctr':c.objective==='leads'?'cpl':'contribution';
  const readyButton=<Button className="mc-primary" onClick={()=>setModal({kind:'settings'})}>ตั้งค่าแคมเปญ ↗</Button>;
  const nextTask=c.tasks.filter(t=>t.status!=='Done').sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,4);
  const offerRows=OFFERS.filter(o=>offer==='all'||o.id===offer).map(o=>{const v=measure(c,{...scope,offer:o.id});return {offer:o.name,started:o.id==='normal'?c.start||'ยังไม่กำหนด':c.releases.find(r=>r.offer===o.id)?.date||'ยังไม่เปิด',units:v.units,revenue:v.revenue,spend:v.spend,mature:v.mature,pending:v.pending,cvr:v.cvr,contribution:v.contribution};});
  return <article className="mc-app" data-reviewed-rows>
    <div className="mc-toolbar"><div className="mc-campaign"><ZuriGoLogo compact/><Dropdown label="Campaign" showLabel value={c.id} choices={ws.campaigns.map(c=>c.id)} choiceLabels={Object.fromEntries(ws.campaigns.map(c=>[c.id,c.name]))} onChange={changeCampaign}/><Button onClick={()=>setModal({kind:'new'})} aria-label="เพิ่มแคมเปญ">＋</Button></div><div className="mc-toolbar-actions"><Field label="Review ณ วันที่" type="date" value={asOf} max={today()} onChange={v=>{if(v){setAsOf(v);setRange('');}}}/><Button onClick={()=>setModal({kind:'settings'})}>ตั้งค่า</Button><Button className="mc-primary" onClick={()=>setModal({kind:'add'})}>＋ บันทึกข้อมูล</Button></div></div>
    <div className="mc-context"><span><i className="mc-dot"/> {OBJECTIVES[c.objective]} · {c.start&&c.end?`${dateLabel(c.start)} – ${dateLabel(c.end)}`:'ยังไม่กำหนดช่วงแคมเปญ'}</span><span>Manual workspace · Target v{c.version} · {serverBusinessId?'PostgreSQL':'บันทึกใน browser นี้'}</span></div>
    {storageError&&<div role="alert" className="mc-errors">{storageError} <Button onClick={doBackup}>Backup ข้อมูลที่เห็น</Button><Button onClick={()=>window.location.reload()}>โหลดใหม่</Button></div>}
    {notice&&<div className="mc-notice" role="status">{notice}<button type="button" aria-label="ปิดข้อความ" onClick={()=>setNotice('')}>×</button></div>}
    {view==='overview'&&<>
      <PhaseRail campaign={c} gate={g}/>
      <div className="mc-overview-grid">
        <section className={`mc-gate ${g.tone}`}><div className="mc-kicker">NEXT DECISION <span>{g.reviewDate?dateLabel(g.reviewDate):'D7 review'}</span></div><Badge tone={g.tone}>{g.status}</Badge><h2>{STATUS[g.status]}</h2><p>{g.message}</p><div className="mc-gate-stats"><span>Phase<strong>{offerName(g.phase.offer)}</strong></span><span>{c.objective==='awareness'?'Impressions':'Mature leads'}<strong>{fmt(c.objective==='awareness'?g.m.impressions:g.m.mature)} <small>/ {fmt(c.minSample)}</small></strong></span></div><ul>{[...g.hard,...g.missing,...g.cautions].slice(0,3).map((s,i)=><li key={i}>{s}</li>)}</ul><Button className="mc-primary" onClick={()=>g.missing.length?setModal({kind:'settings'}):setModal({kind:'decision'})}>{g.missing.length?'เติมข้อกำหนดเพื่อเริ่มวัดผล':'บันทึกผล review'} ↗</Button><small>DESTINY 1 องค์ / 5,555 บาท · เปิดเมื่อ Normal ต่ำกว่าเกณฑ์และผ่าน gate</small></section>
        <div className="mc-outcomes"><div className="mc-metrics-row"><Metric accent name={PRIMARY[c.objective][1]} value={metricFormat(g.primaryKey,m[g.primaryKey])} unit={PRIMARY[c.objective][2]} caption={`Mid goal ${fmt(c.targets.mid)} · pace ${targetBand(m[g.primaryKey],{low:g.lowToDate,mid:g.midToDate,high:g.highToDate})}`} onClick={()=>openMetric(g.primaryKey)}/><Metric name="Media spend" value={fmt(m.spend)} unit="บาท" caption={`Released cap ${fmt(c.cap)} · เหลือหลังภาระ ${fmt(g.remainingBudget)}`} onClick={()=>openMetric('spend')}/><Metric name={DEFINITIONS[supportKey][0]} value={metricFormat(supportKey,m[supportKey])} unit={supportKey==='ctr'?'':'บาท'} caption={supportKey==='contribution'?(m.costKnown?`Margin ${pct(m.margin)} · floor ${fmt(c.marginFloor)}%`:'รอต้นทุนครบทั้ง 6 รายการและ media'):DEFINITIONS[supportKey][2]} onClick={()=>openMetric(supportKey)}/></div>
          <Evidence id="mc-target-trend" title="Actual เทียบเส้นเป้าหมาย" chart={chartSpec} rows={chartRows} sourceRows={[...m.orderRows,...m.ads,...m.leads,{recordType:'target-settings',...settingsSnapshot(c)}]} description="Cumulative actual ตามวันที่เหตุการณ์; Low/Mid/High เฉลี่ยเท่ากันทุกวันปฏิทินเป็นสมมติฐานวางแผน ช่องว่างคือไม่มีข้อมูล ยอดอาจปรับเมื่อมีคืนเงิน/สินค้า">
            {chartRows.length?<div className="mc-chart"><Chart spec={chartSpec} rows={chartRows} {...shell.chartProps('mc-target-trend')}/></div>:<Empty title="เริ่มจากกำหนดวันและเป้า">เมื่อกรอกวันที่จะแสดงเส้นแผน และแสดง Actual เมื่อมี records จริง {c.objective==='inventory'&&<>· เป้า Mid จาก M01 คือ <b>108 units</b></>}</Empty>}
            <p className="mc-note">Target to date: Low {fmt(g.lowToDate,1)} / Mid {fmt(g.midToDate,1)} · Actual {fmt(m[g.primaryKey],1)} · ไม่มี actual จะไม่วาดเส้นสมมติ</p>
          </Evidence>
        </div>
      </div>
      <div className="mc-bottom-grid"><Panel title="งานที่ต้องไปต่อ" action={<Button onClick={()=>openRecord('tasks')}>＋ เพิ่มงาน</Button>}>{nextTask.length?<div className="mc-task-list">{nextTask.map(t=><button key={t.id} onClick={()=>openRecord('tasks',t)}><span><strong>{t.title}</strong><small>{t.owner||'ยังไม่มี owner'} · {dateLabel(t.due)}</small></span><Badge tone={t.status==='Blocked'?'bad':'neutral'}>{t.status}</Badge></button>)}</div>:<Empty title="ยังไม่มีงานที่บันทึก">เริ่มจากงานตรวจ tracking, ราคา, stock หรือเตรียม creative ตามสิ่งที่ยังขาด</Empty>}</Panel><Companion view={view}/></div>
      <div className="mc-health-strip"><span>ข้อมูลครบถึง</span>{Object.entries(c.sources).map(([key,date])=><button key={key} onClick={()=>setModal({kind:'settings'})}><span>{key}</span><strong>{date?dateLabel(date):'รอยืนยัน'}</strong></button>)}</div>
    </>}
    {view==='performance'&&<>
      <div className="mc-filter-row"><Dropdown label="Offer" showLabel value={offer} choices={['all',...OFFERS.map(o=>o.id)]} choiceLabels={{all:'ทุก offer',...Object.fromEntries(OFFERS.map(o=>[o.id,o.name]))}} onChange={setOffer}/><Dropdown label="Channel" showLabel value={channel} choices={['all',...new Set([...c.ads,...c.leads,...c.orders].map(r=>r.channel).filter(Boolean))]} choiceLabels={{all:'ทุก channel'}} onChange={setChannel}/><DateRangePicker label="ช่วงวันที่" choices={Array.from({length:c.start&&dayDiff(c.start,asOf)>=0?Math.min(367,dayDiff(c.start,asOf)+1):0},(_,i)=>plusDays(c.start,i))} value={range||`${c.start}..${asOf}`} onChange={setRange}/><Button onClick={()=>{setOffer('all');setChannel('all');setRange('');}}>ล้างตัวกรอง</Button><Button onClick={scopedExport}>Export view</Button></div>
      <div className="mc-section-label"><h2>ผลลัพธ์และจุดที่ต้องตรวจ</h2><span>{dateLabel(scope.from)} – {dateLabel(scope.to)} · Bangkok</span></div>
      <div className="mc-diagnostic-grid">{cards.map(([key,label])=><Metric key={key} name={label} value={metricFormat(key,pm[key])} caption={key==='cvr'?`${pm.converted} / ${pm.mature} mature · pending ${pm.pending}`:key==='units'?`Paid-unfulfilled ${fmt(pm.unfulfilled)} units`:DEFINITIONS[key]?.[2]} onClick={()=>openMetric(key,scope)}/>)}</div>
      <div className="mc-two-col"><Panel title="Lead journey"><div className="mc-funnel">{[['leadCount','Acquired leads'],['mql','MQL entries'],['sql','SQL entries'],['orders','Paid orders']].map(([key,label])=><button key={key} onClick={()=>openMetric(key,scope)}><strong>{fmt(pm[key])}</strong><span>{label} ↗</span></button>)}</div><p className="mc-note">เป็น stage-entry flow คนละวันกับ acquisition; จึงไม่หารขั้นต่อขั้น · Mature conversion {pm.converted}/{pm.mature}, pending {pm.pending}</p><p className="mc-definition">{c.definition||'ยังไม่ระบุเกณฑ์ MQL / SQL และ qualified traffic'}</p></Panel><Companion view={view}/></div>
      <Evidence id="mc-offer-performance" title="เทียบ offer พร้อมตัวหารและระยะเปิดจริง" rows={offerRows} sourceRows={[...pm.ads,...pm.leads,...pm.orderRows]} description="Acquisition offer ใช้กับ lead และ media; purchased offer ใช้กับ order การเปลี่ยน offer ต่างสัปดาห์เป็น observation ไม่ใช่ causal uplift"><DataTable caption="ผลแยก offer" searchable={false} columns={[{field:'offer',label:'Offer'},{field:'started',label:'เริ่มจริง'},{field:'units',label:'Net units'},{field:'revenue',label:'Revenue ฿'},{field:'spend',label:'Spend ฿'},{field:'mature',label:'Mature leads'},{field:'pending',label:'Pending'},{field:'cvr',label:'CVR',renderCell:pct},{field:'contribution',label:'Contribution ฿'}]} rows={offerRows} onRowSelect={row=>setOffer(OFFERS.find(o=>o.name===row.offer).id)} rowKey="offer" rowActionLabel={row=>`ดู ${row.offer}`}/></Evidence>
      <div className="mc-two-col"><Panel title="ช่วงก่อนหน้าเทียบช่วงที่เลือก"><PeriodComparison campaign={c} scope={scope}/></Panel><Panel title="Stock ที่พร้อมขาย ณ วันสิ้นช่วง"><div className="mc-table-scroll"><table><thead><tr><th>SKU</th><th>Available</th><th>Reserved</th><th>Overstock</th></tr></thead><tbody>{stockAt(c,scope.to).map(s=><tr key={s.sku}><th>{s.sku}</th><td>{fmt(s.available)}</td><td>{fmt(s.reserved)}</td><td>{fmt(s.overstock)}</td></tr>)}</tbody></table></div>{!c.inventory.length&&<p className="mc-note">ยังไม่มี stock snapshot</p>}<div className="mc-capacity">{OFFERS.slice(1).map(o=><span key={o.id}>{o.name}<b>{fmt(capacity(c,o.id,scope.to))} ชุด</b></span>)}</div><p className="mc-note">Available = sellable − reserved; capacity แต่ละ offer ใช้ stock กองเดียวกัน จึงบวกกันไม่ได้</p></Panel></div>
      <Panel title="ข้อมูลที่ใช้ในมุมมองนี้" action={<Button className="mc-primary" onClick={()=>openRecord(ledger)}>＋ บันทึก {ledger}</Button>}><SegmentedControl value={ledger} options={Object.keys(RECORD_LABELS).filter(k=>k!=='tasks').map(value=>({value,label:value}))} onChange={setLedger}/><Ledger type={ledger} rows={ledger==='ads'?pm.ads:ledger==='leads'?[...new Map([...pm.leads,...pm.stageRows].map(r=>[r.id,r])).values()]:ledger==='orders'?pm.orderRows:stockAt(c,scope.to)} onEdit={r=>openRecord(ledger,r)}/></Panel>
    </>}
    {view==='plan'&&<>
      <PhaseRail campaign={c} gate={g}/><div className="mc-two-col"><Panel title="เป้าหมายที่ใช้ตัดสินใจ" action={readyButton}><div className="mc-targets">{['low','mid','high'].map(k=><div key={k}><span>{k.toUpperCase()}</span><strong>{fmt(c.targets[k])}</strong><small>{PRIMARY[c.objective][2]}</small></div>)}</div><p className="mc-note">{PRIMARY[c.objective][1]} · ค่าเท่าขอบเขตนับเข้าระดับนั้น · เส้นแผนเฉลี่ยตามวันปฏิทิน</p><dl className="mc-facts"><div><dt>Budget cap / committed</dt><dd>{fmt(c.cap)} / {fmt(c.committed)} บาท</dd></div><div><dt>Margin floor</dt><dd>{fmt(c.marginFloor)}%</dd></div><div><dt>Window / minimum sample</dt><dd>{fmt(c.windowDays)} วัน / {fmt(c.minSample)}</dd></div><div><dt>Normal CVR · low / mid / high</dt><dd>{fmt(c.normalLow)} / {fmt(c.normalMid)} / {fmt(c.normalHigh)} %</dd></div></dl></Panel><Companion view={view}/></div>
      <Panel title="Review gates · ตรวจตามลำดับ"><div className="mc-gate-checks">{[
        ['01','Hard constraints',g.hard.length?'BLOCK':'ไม่มี breach ที่ยืนยัน',g.hard.join(' · ')||'งบ / margin / stock ตรวจจากข้อมูลที่มี',g.hard.length?'bad':'neutral'],
        ['02','Data eligibility',g.missing.length?'DATA HOLD':'ผ่าน',g.missing.join(' · ')||'แหล่งที่เกี่ยวข้องครบตาม freshness ที่ตั้งไว้',g.missing.length?'warn':'good'],
        ['03','Sample & maturity',g.fullWeek&&g.enough?'ผ่าน':'LEARNING',`${fmt(g.elapsed)} วันจากเปิด · ${g.m.mature} mature / ${fmt(c.minSample)} ขั้นต่ำ · ${g.m.pending} pending`,g.fullWeek&&g.enough?'good':'warn'],
        ['04','Performance band',g.status,`${pct(g.m.cvr)} CVR (${g.m.converted}/${g.m.mature}) · ${fmt(m[g.primaryKey])} actual / ${fmt(g.lowToDate,1)} Low pace`,g.tone],
        ['05','Action readiness',g.canRelease?'พร้อมให้ owner พิจารณา':'ยังเปิด offer ไม่ได้',[...g.cautions,`เหลือ ${fmt(g.daysLeft)} วัน; test ใหม่ต้องมีอย่างน้อย 7 วัน`].join(' · '),g.canRelease?'good':'warn'],
        ['06','Owner decision','ต้องบันทึก','Continue / fix / release / scale / pause / close · แพ็กเกจแรก DESTINY','neutral']
      ].map(([n,title,status,desc,tone])=><div key={n}><b>{n}</b><div><strong>{title}</strong><p>{desc}</p></div><Badge tone={tone}>{status}</Badge></div>)}</div><div className="mc-form-actions"><Button onClick={()=>setModal({kind:'decision'})}>บันทึกคำตัดสิน</Button><Button className="mc-primary" onClick={()=>setModal({kind:'release'})}>ยืนยันเปิดจริง ↗</Button></div></Panel>
      <div className="mc-band-rules"><span><b>≤ 2%</b> FIX / NO SCALE</span><span><b>&gt; 2% – &lt; 5%</b> Learning</span><span><b>≥ 5% – &lt; 10%</b> Base review</span><span><b>≥ 10%</b> High review</span></div><p className="mc-note">กติกา package จากแผน M01 · ผล CVR ดีไม่ได้ข้าม budget, margin, stock, SLA หรือ data hold</p>
      <fieldset className="mt-access-fields" disabled={!canWrite}><Forecast campaign={c} actual={m} onSave={forecast=>update(d=>({...d,forecast}),'บันทึก scenario reforecast แล้ว; actual ไม่เปลี่ยน')}/></fieldset>{!canWrite&&<Button onClick={()=>requestWrite(null)}>แก้ไข Scenario</Button>}
      <SortableRegion id="mc-plan-sources" variant="canvas" columns={12} spacing="standard" rows={[{id:'mc-source-offers',items:['mc-original-offers']},{id:'mc-source-scenarios',items:['mc-original-scenarios']}]}>
        <SortableItem id="mc-original-offers" label="M01 offer assumptions" kind="table" span={12}><DataComponent id="mc-original-offers" title="M01 · ราคาและส่วนผสมจากแผนเดิม" queryId="m1_plan" kind="table" variant="card" sourceRows={shell.reviewedRows('m1_plan')} displayRows={shell.reviewedRows('m1_plan')} description="Original planning reference, not actuals. Normal-first sequence replaces the original simultaneous offer mix."><DataTable searchable={false} caption="M01 offers" rows={shell.reviewedRows('m1_plan')} columns={[{field:'name',label:'Offer'},{field:'price',label:'ราคา ฿'},{field:'unitsPerOrder',label:'Units / order'},{field:'plannedOrders',label:'Modeled orders'},{field:'cpl',label:'CPL assumption ฿'},{field:'packaging',label:'Packaging ฿'}]}/></DataComponent></SortableItem>
        <SortableItem id="mc-original-scenarios" label="M01 scenarios" kind="table" span={12}><DataComponent id="mc-original-scenarios" title="M01 · Low / Mid / High scenarios" queryId="m1_scenarios" kind="table" variant="card" sourceRows={shell.reviewedRows('m1_scenarios')} displayRows={shell.reviewedRows('m1_scenarios')} description="43 orders / 108 units. Modeled assumptions do not authorize budget. Contribution excludes shipping, fees, commission and other operations."><DataTable searchable={false} caption="M01 scenarios" rows={shell.reviewedRows('m1_scenarios')} columns={[{field:'scenario',label:'Scenario'},{field:'conversion',label:'CVR %'},{field:'leads',label:'Leads'},{field:'revenue',label:'Revenue ฿'},{field:'media',label:'Modeled media ฿'},{field:'contribution',label:'Contribution* ฿'}]}/><p className="mc-note">*หักเฉพาะสินค้า บรรจุภัณฑ์ และสื่อ ยังไม่ใช่กำไรสุทธิ · 15,000–20,000 บาทเป็นงบทดสอบที่เสนอในเอกสาร ไม่ใช่งบที่ปล่อยแล้ว</p></DataComponent></SortableItem>
      </SortableRegion>
      <Panel title="ประวัติ target / rule versions">{c.history.filter(h=>h.type==='settings').length?<div className="mc-history">{c.history.filter(h=>h.type==='settings').slice().reverse().map(h=><button key={h.id} onClick={()=>setModal({kind:'history',entry:h})}><b>v{h.version}</b><span>{h.reason}<small>{h.owner} · ใช้ตั้งแต่ {dateLabel(h.effective)}</small></span><span>ดู version ก่อนเปลี่ยน ↗</span></button>)}</div>:<p className="mc-note">ยังไม่มีการเปลี่ยนเกณฑ์ · MUJEEN v1 มีเพียง Mid 108 units จากแผน</p>}</Panel>
    </>}
    {view==='work'&&<>
      {linkedTasks}
      <div className="mc-section-label"><h2>จากสิ่งที่พบ → สิ่งที่ต้องทำ</h2><Button className="mc-primary" onClick={()=>openRecord('tasks')}>＋ เพิ่มงาน</Button></div>
      <div className="mc-work-counts">{['Backlog','Ready','Doing','Blocked','Review','Done'].map(s=><button className={taskStatus===s?'selected':''} key={s} onClick={()=>setTaskStatus(taskStatus===s?'all':s)}><strong>{c.tasks.filter(t=>t.status===s).length}</strong><span>{s}</span></button>)}</div>
      <Panel title="งานของแคมเปญ"><div className="mc-task-cards">{c.tasks.filter(t=>taskStatus==='all'||t.status===taskStatus).map(t=><button key={t.id} onClick={()=>openRecord('tasks',t)}><div><Badge tone={t.status==='Blocked'?'bad':t.status==='Done'?'good':'neutral'}>{t.status}</Badge><span>{t.priority}</span></div><h3>{t.title}</h3><p>{t.action||t.hypothesis||'ยังไม่มีรายละเอียด'}</p><footer><span>{t.owner||'ยังไม่มี owner'} · {dateLabel(t.due)}</span><small>{t.recheck?`ตรวจ KPI ซ้ำ ${dateLabel(t.recheck)}`:'ยังไม่นัดตรวจ KPI'}</small></footer></button>)}</div>{!c.tasks.filter(t=>taskStatus==='all'||t.status===taskStatus).length&&<Empty title={taskStatus==='all'?'ยังไม่มีงาน':'ไม่มีงานตรงตัวกรองนี้'}>กำหนด owner, วันส่ง, เกณฑ์รับงาน และวันกลับมาวัดผล</Empty>}</Panel>
      <div className="mc-two-col"><Panel title="ข้อค้างและการรับทราบ"><div className="mc-alerts">{alerts.map(a=><div key={a.id}><div><strong>{a.id} · {a.title}</strong><small>พบล่าสุด {dateLabel(a.lastObserved)}{a.owner&&` · ${a.owner}`}</small></div><Badge tone={a.status==='Acknowledged'?'neutral':'warn'}>{a.status}</Badge><Button onClick={()=>setModal({kind:'ack',alert:a})}>{a.status==='Acknowledged'?'ดู / อัปเดต':'รับทราบ'}</Button></div>)}</div>{!alerts.length&&<p className="mc-note">ไม่พบเงื่อนไขค้างจากข้อมูลปัจจุบัน</p>}<p className="mc-note">หนึ่งรายการต่อ gate ต่อแคมเปญ · รับทราบไม่ได้แปลว่าแก้แล้ว รายการหายจากคิวเมื่อเงื่อนไขผ่าน และเก็บประวัติการรับทราบไว้</p></Panel><Companion view={view}/></div>
    </>}
    {view==='review'&&<>
      <div className="mc-two-col"><div>{!canWrite&&<Button onClick={()=>requestWrite(null)}>เขียน Review</Button>}<fieldset className="mt-access-fields" disabled={!canWrite}><ReviewEditor key={c.id+asOf} campaign={c} asOf={asOf} onSave={text=>update(d=>{d.reviews.push({id:uid(),date:asOf,text,snapshot:evidenceSnapshot(d,asOf)});return d;},'เก็บ review snapshot แล้ว')} notify={setNotice}/></fieldset></div><Companion view={view}/></div>
      <Panel title="คำตัดสินและการเปิดขาย" action={<div className="mc-inline-actions"><Button onClick={()=>setModal({kind:'release'})}>ยืนยันเปิดจริง</Button><Button className="mc-primary" onClick={()=>setModal({kind:'decision'})}>＋ บันทึกคำตัดสิน</Button></div>}>{c.decisions.length?<div className="mc-history">{c.decisions.slice().reverse().map(d=><button key={d.id} onClick={()=>setModal({kind:'decisionDetail',entry:d})}><Badge tone={d.action==='pause'?'warn':'neutral'}>{d.action}</Badge><span><strong>{offerName(d.offer)} · {d.reason}</strong><small>{d.owner} · {dateLabel(d.date)} · ตรวจซ้ำ {dateLabel(d.nextReview)}</small></span><span>snapshot v{d.snapshot.version} ↗</span></button>)}</div>:<Empty title="ยังไม่มีคำตัดสิน">ครบหนึ่งสัปดาห์ให้บันทึก review แม้สรุปว่า “ข้อมูลยังไม่พอ”</Empty>}{c.releases.length>0&&<div className="mc-release-log">{c.releases.map(r=><p key={r.id}><b>{offerName(r.offer)}</b> เปิดจริง {dateLabel(r.date)} → Review {dateLabel(plusDays(r.date,7))} · {r.evidence}</p>)}</div>}</Panel>
      <Panel title="Review snapshots ที่เก็บไว้">{c.reviews.length?<div className="mc-history">{c.reviews.slice().reverse().map(r=><button key={r.id} onClick={()=>setModal({kind:'reviewDetail',entry:r})}><strong>{dateLabel(r.date)}</strong><span>Target v{r.snapshot.version} · {r.snapshot.gate.status}</span><span>ดู / Export ↗</span></button>)}</div>:<p className="mc-note">บันทึก summary เพื่อเก็บตัวเลข ข้อกำหนด และหลักฐาน ณ เวลาที่ตัดสินใจ</p>}</Panel>
    </>}
    <footer className="mc-footer"><span>ข้อมูลจริงกรอกเอง · Local workspace · M01 เป็นแผนอ้างอิง</span><div><Button onClick={doBackup}>{serverBusinessId?'Backup แคมเปญและงาน':'Backup JSON'}</Button><Button onClick={()=>requestWrite(()=>importInput.current?.click())}>Restore backup</Button><input ref={importInput} hidden type="file" accept=".json,application/json" onChange={e=>importBackup(e.target.files?.[0])}/></div></footer>
    {modal?.kind==='settings'&&<SettingsForm campaign={c} onClose={()=>setModal(null)} onSave={(settings,meta)=>{update(d=>({...d,...settings,version:d.version+1,history:[...d.history,{id:uid(),type:'settings',version:d.version+1,...meta,previous:settingsSnapshot(d),recordedAt:new Date().toISOString()}]}),'บันทึกเป้าและเกณฑ์ version ใหม่แล้ว');setModal(null);}}/>}
    {modal?.kind==='record'&&<RecordForm type={modal.type} campaign={c} record={modal.record} seed={modal.seed} onClose={()=>setModal(null)} onSave={r=>{update(d=>{const i=d[modal.type].findIndex(x=>x.id===r.id);if(i>=0){d.history.push({id:uid(),type:'correction',collection:modal.type,recordId:r.id,previous:d[modal.type][i],recordedAt:new Date().toISOString()});d[modal.type][i]=r;}else d[modal.type].push(r);return d;});setModal(null);}}/>}
    {modal?.kind==='decision'&&<DecisionForm campaign={c} onClose={()=>setModal(null)} onSave={r=>{update(d=>{d.decisions.push({...r,snapshot:evidenceSnapshot(d,r.date)});return d;},'เก็บคำตัดสินและหลักฐานแล้ว');setModal(null);}}/>}
    {modal?.kind==='release'&&<ReleaseForm campaign={c} onClose={()=>setModal(null)} onSave={r=>{update(d=>{d.releases.push(r);return d;},`บันทึกเปิด ${offerName(r.offer)} จริง; review ${plusDays(r.date,7)}`);setModal(null);}}/>}
    {modal?.kind==='add'&&<Modal title="บันทึกข้อมูลของแคมเปญ" onClose={()=>setModal(null)} wide={false}><div className="mc-entry-options">{Object.entries(RECORD_LABELS).map(([k,v])=><button key={k} onClick={()=>openRecord(k)}><strong>{v}</strong><span>บันทึก / แก้ไขตาม Source ID ↗</span></button>)}</div></Modal>}
    {modal?.kind==='new'&&<NewCampaign onClose={()=>setModal(null)} onSave={async(name,objective)=>{if(storageError)return;const campaign=createCampaign(name,objective,false);if(!await persist({...ws,selected:campaign.id,campaigns:[...ws.campaigns,campaign]}))return;setOffer('all');setChannel('all');setRange('');setModal({kind:'settings'});}}/>}
    {modal?.kind==='ack'&&<Acknowledge alert={modal.alert} onClose={()=>setModal(null)} onSave={r=>{update(d=>{d.alertActions.push({...r,id:uid(),ruleId:modal.alert.id,action:'ack',date:asOf});return d;},'รับทราบแล้ว; gate ยังรอการแก้เงื่อนไข');setModal(null);}}/>}
    {['history','decisionDetail','reviewDetail'].includes(modal?.kind)&&<Modal title={modal.kind==='history'?'Version ก่อนเปลี่ยน':modal.kind==='decisionDetail'?'คำตัดสินและหลักฐาน ณ วัน review':'Review snapshot'} onClose={()=>setModal(null)}><SnapshotDetail kind={modal.kind} entry={modal.entry}/><Button onClick={()=>download(`mission-control-${modal.entry.id}.json`,modal.entry)}>Export snapshot</Button></Modal>}
    {detail&&<MetricDetail campaign={c} detail={detail} onClose={()=>setDetail(null)} onTask={()=>{setModal({kind:'record',type:'tasks',seed:{gate:detail.key,title:`ตรวจ ${DEFINITIONS[detail.key]?.[0]||detail.key}`,offer:detail.scope.offer&&detail.scope.offer!=='all'?detail.scope.offer:g.phase.offer,hypothesis:`ตรวจข้อมูลช่วง ${detail.scope.from||c.start} – ${detail.scope.to}; channel ${detail.scope.channel||'all'}`}});setDetail(null);}}/>}
  </article>;
}



