import React, {useState} from 'react';
import {Button, Dialog} from '../../data-app-public.jsx';
import {OFFERS, OBJECTIVES, PRIMARY, COSTS, today, uid, num, validateRecord, validateSettings, validateRelease, settingsSnapshot} from '../shared/model.mjs';

export const offerName = id => OFFERS.find(o=>o.id===id)?.name||id;
export const fmt = (v,d=0) => v==null?'—':Number(v).toLocaleString('th-TH',{maximumFractionDigits:d});
export const pct = v => v==null?'—':`${fmt(v*100,2)}%`;
export function Field({label,value,onChange,type='text',hint,options,wide=false,...props}){
  return <label className={`mc-field ${wide?'wide':''}`}><span>{label}</span>{options?<select aria-label={label} aria-description={hint} value={value??''} onChange={e=>onChange(e.target.value)} {...props}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:type==='textarea'?<textarea aria-label={label} aria-description={hint} value={value??''} onChange={e=>onChange(e.target.value)} rows={3} {...props}/>:<input aria-label={label} aria-description={hint} type={type} value={value??''} onChange={e=>onChange(type==='number'?num(e.target.value):e.target.value)} step={type==='number'?'any':undefined} {...props}/>} {hint&&<small>{hint}</small>}</label>;
}
export function Errors({errors}){return errors.length>0&&<div className="mc-errors" role="alert"><strong>ยังบันทึกไม่ได้</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>;}
export function Modal({title,children,onClose,wide=true}){return <Dialog open onClose={onClose} title={title} expanded={wide}><div className="mc-modal">{children}</div></Dialog>;}
export function SettingsForm({campaign,onSave,onClose}){
  const [draft,setDraft]=useState(()=>settingsSnapshot(campaign)),[reason,setReason]=useState(''),[effective,setEffective]=useState(today()),[errors,setErrors]=useState([]);
  const set=(k,v)=>setDraft(d=>({...d,[k]:v}));
  const f=(k,label,type='number',hint)=> <Field key={k} label={label} value={draft[k]} type={type} hint={hint} onChange={v=>set(k,v)}/>;
  function save(e){e.preventDefault();const es=validateSettings(draft);if(!draft.owner.trim()||!reason.trim())es.push('ระบุผู้รับผิดชอบและเหตุผลการเปลี่ยน');if(effective>today()||!effective)es.push('วันที่เริ่มใช้ต้องไม่อยู่ในอนาคต');if(campaign.start!==draft.start||campaign.end!==draft.end){const dates=['ads','leads','orders','inventory'].flatMap(k=>campaign[k].map(r=>r.date));if(dates.some(d=>draft.start&&d<draft.start||draft.end&&d>draft.end))es.push('ช่วงวันที่ใหม่จะตัด actual records ที่มีอยู่');}setErrors(es);if(!es.length)onSave(draft,{reason,effective,owner:draft.owner});}
  return <Modal title="ตั้งค่าแคมเปญและเกณฑ์วัดผล" onClose={onClose}><form onSubmit={save}>
    <p className="mc-note">ช่องว่าง = ยังไม่กำหนด · 108 units มาจากแผน MUJEEN เท่านั้น · บันทึกแต่ละครั้งเก็บ version เดิมไว้</p>
    <div className="mc-form-grid">{f('name','ชื่อแคมเปญ','text')}<Field label="Objective" value={draft.objective} options={Object.entries(OBJECTIVES).map(([value,label])=>({value,label}))} onChange={v=>setDraft(d=>({...d,objective:v,targets:{low:null,mid:null,high:null}}))}/>{f('owner','ผู้รับผิดชอบ','text')}{f('start','วันเริ่ม','date')}{f('end','วันสิ้นสุด','date')}</div>
    <h3>เป้าหมาย · {PRIMARY[draft.objective][1]}</h3><div className="mc-form-grid three">{['low','mid','high'].map(k=><Field key={k} label={`${k.toUpperCase()} · ${PRIMARY[draft.objective][2]}`} type="number" min="0" value={draft.targets[k]} onChange={v=>setDraft(d=>({...d,targets:{...d.targets,[k]:v}}))}/>)}</div>
    <p className="mc-note">เส้น pacing เฉลี่ยเท่ากันทุกวันปฏิทิน เป็นสมมติฐานวางแผน · เปลี่ยน objective จะล้างเป้าเดิม</p>
    <h3>งบและความพร้อม</h3><div className="mc-form-grid">{f('cap','Released budget cap · บาท')}{f('committed','Committed spend · บาท','number','ภาระที่ยืนยันแต่ยังไม่รวมใน spend จริง; ใส่ 0 เมื่อตรวจว่าไม่มี')}{f('marginFloor','Contribution margin floor · %')}{f('minSample',draft.objective==='awareness'?'ขั้นต่ำ impressions':'ขั้นต่ำ mature leads')}{draft.objective!=='awareness'&&f('windowDays','Conversion window · วัน')}{f('maxDataAgeDays','อายุข้อมูลที่ยอมรับ · วัน')}{f('responseSLA','Response SLA · นาที','number','นับนาทีจริงต่อเนื่อง; ไม่รวม bot reply')}</div>
    <h3>Normal sales cutoff · CVR %</h3><div className="mc-form-grid three">{f('normalLow','≤ ค่านี้: FIX / NO SCALE')}{f('normalMid','≥ ค่านี้: Base review')}{f('normalHigh','≥ ค่านี้: High review')}</div>
    <p className="mc-note">Package ใช้ ≤2% / &gt;2–&lt;5% / ≥5–&lt;10% / ≥10% จาก M01; Normal มีเกณฑ์แยก ถ้ายังไม่ตั้งจะดู KPI pace เท่านั้น</p>
    <div className="mc-form-grid"><Field label="นิยาม qualified / MQL / SQL" type="textarea" wide value={draft.definition} onChange={v=>set('definition',v)} hint="เกณฑ์คัด lead, qualified session, วันเริ่ม stage และเงื่อนไขผู้ซื้อที่ใช้จริง"/><Field label="ขอบเขตบัญชีและ attribution" type="textarea" wide value={draft.accounting} onChange={v=>set('accounting',v)} hint="ระบุ VAT / shipping / ส่วนลด / ค่าใช้จ่ายที่รวม; channel เป็น acquisition channel จาก CRM ไม่ใช่ ROAS ของ platform"/></div>
    <h3>Source coverage · ข้อมูลครบตั้งแต่วันเริ่มถึงวันที่</h3><p className="mc-note">กรอกหลังตรวจยอดครบเท่านั้น รวมวันที่ไม่มีเหตุการณ์เป็น 0; ไม่ใช่เวลาที่เปิดหน้า dashboard</p><div className="mc-form-grid">{['ads','leads','orders','inventory'].map(k=><Field key={k} label={k} type="date" max={today()} value={draft.sources[k]} onChange={v=>setDraft(d=>({...d,sources:{...d.sources,[k]:v}}))}/>)}</div>
    <h3>Bundle BOM</h3><div className="mc-form-grid">{['pair','complete'].map(k=><Field key={k} label={offerName(k)} value={draft.boms[k]} placeholder="SKU-A:1,SKU-B:1" onChange={v=>setDraft(d=>({...d,boms:{...d.boms,[k]:v}}))}/>)}</div>
    <div className="mc-form-grid"><Field label="เหตุผลที่ตั้ง/เปลี่ยนเกณฑ์" type="textarea" value={reason} onChange={setReason} required/><Field label="วันที่เริ่มใช้ version นี้" type="date" value={effective} onChange={setEffective} max={today()} required/></div><Errors errors={errors}/><div className="mc-form-actions"><Button type="button" onClick={onClose}>ยกเลิก</Button><Button type="submit" className="mc-primary">บันทึก version {campaign.version+1}</Button></div>
  </form></Modal>;
}
export const RECORD_LABELS={ads:'Ad / traffic observation',leads:'Lead / MQL / SQL',orders:'Order / cost / fulfillment',inventory:'Inventory snapshot',tasks:'งานและหลักฐาน'};
const blank = (type,c) => {
  const common={id:uid(),date:today(),offer:'normal',channel:'',evidence:'',note:''};
  if(type==='ads')return {...common,spend:null,impressions:null,clicks:null,qualifiedVisits:null,creative:'',placement:'',audience:''};
  if(type==='leads')return {...common,mqlAt:'',sqlAt:'',responseMinutes:null,exposedOffer:'',requestedOffer:'',lostReason:'',audience:''};
  if(type==='orders')return {...common,leadId:'',customerId:'',newCustomer:false,status:'paid',amount:null,refund:0,refundAt:'',cancelledAt:'',units:null,fulfilled:0,fulfilledAt:'',returned:0,returnedAt:'',...Object.fromEntries(COSTS.map(k=>[k,null])),returnReason:''};
  if(type==='inventory')return {id:uid(),date:today(),sku:'',sellable:null,reserved:null,target:null,evidence:''};
  return {id:uid(),title:'',status:'Backlog',owner:'',due:'',priority:'Medium',offer:'normal',gate:'',hypothesis:'',action:'',dependencies:'',estimate:null,acceptance:'',evidence:'',recheck:'',outcome:''};
};
export function RecordForm({type,campaign,record,seed={},onSave,onClose}){
  const [r,setR]=useState(()=>record?structuredClone(record):{...blank(type,campaign),...seed}),[errors,setErrors]=useState([]);
  const set=(k,v)=>setR(d=>({...d,[k]:v})),f=(k,label,t='text',hint)=> <Field key={k} label={label} type={t} value={r[k]} onChange={v=>set(k,v)} hint={hint}/>;
  function save(e){e.preventDefault();const es=validateRecord(type,r,campaign);if(!record&&campaign[type].some(x=>x.id===r.id))es.push('ID นี้มีแล้ว ให้เปิด record เดิมเพื่อแก้ไข');if(type==='inventory'&&campaign.inventory.some(x=>x.id!==r.id&&x.date===r.date&&x.sku===r.sku))es.push('SKU/วันเดียวกันมี snapshot แล้ว ให้แก้ไขรายการเดิม');setErrors(es);if(!es.length)onSave({...r,updatedAt:new Date().toISOString()});}
  return <Modal title={`${record?'แก้ไข':'บันทึก'} ${RECORD_LABELS[type]}`} onClose={onClose}><form onSubmit={save}>
    <p className="mc-note">ใช้รหัสจากต้นทางเพื่อป้องกันนับซ้ำ · ช่องว่างคือยังไม่ทราบ ใส่ 0 เฉพาะเมื่อยืนยันแล้ว</p><div className="mc-form-grid"><Field label="Record ID" value={r.id} onChange={v=>set('id',v)} disabled={!!record}/>{type!=='tasks'&&f('date',type==='leads'?'วันที่ได้ lead':type==='orders'?'วันที่ชำระเงิน':'วันที่ข้อมูล','date')}
    {!['inventory'].includes(type)&&<Field label="Offer" value={r.offer} options={OFFERS.map(o=>({value:o.id,label:o.name}))} onChange={v=>set('offer',v)}/>}
    {['ads','leads','orders'].includes(type)&&f('channel',type==='orders'?'Acquisition channel (ว่าง = ตาม Lead ID)':'Acquisition channel')}
    {type==='ads'&&<>{f('spend','Media spend · บาท','number')}{f('impressions','Impressions','number')}{f('clicks','Link clicks','number')}{f('qualifiedVisits','Qualified sessions','number')}{f('creative','Creative / Ad ID')}{f('placement','Placement')}{f('audience','Audience / segment')}</>}
    {type==='leads'&&<>{f('mqlAt','วันที่ผ่าน MQL','date')}{f('sqlAt','วันที่ผ่าน SQL','date')}{f('responseMinutes','เวลาถึงการตอบครั้งแรก · นาที','number')}{f('exposedOffer','Offer ที่เห็น (อาจหลายตัว)')}{f('requestedOffer','Offer ที่ขอข้อมูล')}{f('audience','Audience / segment')}{f('lostReason','เหตุผลที่ไม่ซื้อ / ข้อโต้แย้ง')}</>}
    {type==='orders'&&<>{f('leadId','Lead ID ที่ซื้อ')}{f('customerId','Customer ID')}<Field label="สถานะ" value={r.status} options={['paid','fulfilled','cancelled','void']} onChange={v=>set('status',v)}/><label className="mc-check"><input type="checkbox" checked={r.newCustomer} onChange={e=>set('newCustomer',e.target.checked)}/>ยืนยันว่าเป็นลูกค้าใหม่</label>{f('amount','ยอดชำระหลังส่วนลด · บาท','number')}{f('units','จำนวนที่สั่ง · units','number')}{f('fulfilled','ส่งมอบ · units','number')}{f('fulfilledAt','วันที่ส่งมอบ','date')}{f('returned','คืนสินค้า · units','number')}{f('returnedAt','วันที่คืนสินค้า','date')}{f('refund','คืนเงิน · บาท','number')}{f('refundAt','วันที่คืนเงิน','date')}{f('cancelledAt','วันที่ยกเลิก','date')}{f('returnReason','เหตุผลที่คืน / ยกเลิก')}
      <p className="mc-note wide">ต้นทุนสุทธิของออเดอร์ (บาท) ผูกกับวันที่ซื้อ; หากปรับภายหลัง ตัวเลขเป็น restated actual และ review ที่บันทึกแล้วไม่เปลี่ยน</p>{COSTS.map((k,i)=>f(k,['Product COGS','Packaging','Shipping subsidy','Payment fees','Commission','Other variable costs'][i],'number'))}</>}
    {type==='inventory'&&<>{f('sku','SKU')}{f('sellable','Sellable units','number')}{f('reserved','Reserved units','number')}{f('target','เป้า stock คงเหลือของ SKU','number','ใช้คำนวณ overstock; ไม่ได้กรอก = ยังประเมินไม่ได้')}</>}
    {type==='tasks'&&<>{f('title','ชื่องาน')}<Field label="สถานะงาน" value={r.status} options={['Backlog','Ready','Doing','Blocked','Review','Done']} onChange={v=>set('status',v)}/>{f('owner','ผู้รับผิดชอบ')}{f('due','กำหนดส่ง','date')}<Field label="Priority" value={r.priority} options={['High','Medium','Low']} onChange={v=>set('priority',v)}/>{f('gate','Metric / Gate ที่เกี่ยวข้อง')}{f('hypothesis','ปัญหา / สมมติฐาน','textarea')}{f('action','สิ่งที่จะทำ','textarea')}{f('dependencies','สิ่งที่ต้องรอ')}{f('estimate','ค่าใช้จ่ายประมาณการ · บาท','number')}{f('acceptance','เกณฑ์รับงาน','textarea')}{f('recheck','วันที่ตรวจผล KPI ซ้ำ','date')}{f('outcome','ผลการตรวจซ้ำ','textarea')}</>}
    {f('evidence','หลักฐาน / Source reference','textarea')}{type!=='tasks'&&f('note','หมายเหตุ','textarea')}</div><Errors errors={errors}/><div className="mc-form-actions"><Button type="button" onClick={onClose}>ยกเลิก</Button><Button type="submit" className="mc-primary">บันทึกข้อมูล</Button></div>
  </form></Modal>;
}
export function DecisionForm({campaign,onSave,onClose}){
  const [r,setR]=useState({id:uid(),date:today(),offer:'destiny',action:'continue',owner:'',reason:'',nextReview:'',expiry:'',scope:'',evidence:'',priorOffers:'ยังไม่เปลี่ยนสถานะ offer เดิม'}),[errors,setErrors]=useState([]);
  const f=(k,label,type='text')=><Field key={k} label={label} type={type} value={r[k]} onChange={v=>setR(d=>({...d,[k]:v}))}/>;
  function save(e){e.preventDefault();const es=[];if(!r.owner.trim()||!r.reason.trim()||!r.scope.trim()||!r.nextReview)es.push('ระบุ owner, scope, เหตุผล และวันตรวจซ้ำ');if(!r.date||r.date>today()||r.nextReview<r.date)es.push('ตรวจวันตัดสินใจและวันตรวจซ้ำ');if(r.action==='release'&&!r.evidence.trim())es.push('คำตัดสิน release ต้องมีหลักฐานที่สนับสนุนการเปลี่ยน offer');if(r.action==='override'&&(!r.expiry||r.expiry<r.date))es.push('Override ต้องมีวันหมดอายุ');setErrors(es);if(!es.length)onSave(r);}
  return <Modal title="บันทึกคำตัดสิน" onClose={onClose}><form onSubmit={save}><p className="mc-note">เป็นบันทึกของผู้รับผิดชอบ พร้อม snapshot หลักฐาน ณ วัน review การเปิดขายจริงต้องยืนยันแยกอีกครั้ง</p><div className="mc-form-grid">{f('date','วันที่ตัดสินใจ','date')}<Field label="Action" value={r.action} options={['continue','fix','release','scale','pause','close','inconclusive','override']} onChange={v=>setR(d=>({...d,action:v}))}/><Field label="Offer ที่เกี่ยวข้อง" value={r.offer} options={OFFERS.map(o=>({value:o.id,label:o.name}))} onChange={v=>setR(d=>({...d,offer:v}))}/>{f('owner','ผู้ตัดสินใจ')}{f('scope','ขอบเขต เช่น creative / offer / budget')}{f('reason','เหตุผล','textarea')}{f('evidence','หลักฐานสนับสนุน / ข้อจำกัด','textarea')}{f('priorOffers','สถานะ offer เดิมหลังคำตัดสิน')}{f('nextReview','วันตรวจซ้ำ','date')}{r.action==='override'&&f('expiry','Override หมดอายุ','date')}</div><Errors errors={errors}/><div className="mc-form-actions"><Button type="button" onClick={onClose}>ยกเลิก</Button><Button className="mc-primary" type="submit">เก็บคำตัดสินและ snapshot</Button></div></form></Modal>;
}
export function ReleaseForm({campaign,onSave,onClose}){
  const choices=campaign.decisions.filter(d=>d.action==='release'&&!campaign.releases.some(r=>r.offer===d.offer));
  const [decisionId,setDecision]=useState(choices[0]?.id||''),[date,setDate]=useState(today()),[ready,setReady]=useState(false),[evidence,setEvidence]=useState(''),[errors,setErrors]=useState([]);
  const decision=choices.find(d=>d.id===decisionId);
  function save(e){e.preventDefault();const es=validateRelease(campaign,decision?.offer,date,decisionId,ready);if(!evidence.trim())es.push('ระบุหลักฐานวันเปิดขายจริง');setErrors(es);if(!es.length)onSave({id:uid(),offer:decision.offer,date,decisionId,evidence});}
  return <Modal title="ยืนยันเปิดขายจริง" onClose={onClose} wide={false}><form onSubmit={save}><p className="mc-note">รอบวัดผลนับ 7 วันจากวันที่นี้ · ต้องมีคำตัดสิน release ก่อน</p><div className="mc-form-grid single"><Field label="คำตัดสินที่ใช้" value={decisionId} options={[{value:'',label:'เลือกคำตัดสิน'},...choices.map(d=>({value:d.id,label:`${offerName(d.offer)} · ${d.date} · ${d.owner}`}))]} onChange={setDecision}/><Field label="วันเปิดจริง" type="date" value={date} max={today()} onChange={setDate}/><Field label="หลักฐานการเปิดจริง" type="textarea" value={evidence} onChange={setEvidence}/><label className="mc-check"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/>ตรวจ creative, ราคา, checkout, ทีมขาย และหลักฐานว่าควรเปลี่ยน offer แล้ว</label></div><Errors errors={errors}/><div className="mc-form-actions"><Button type="button" onClick={onClose}>ยกเลิก</Button><Button className="mc-primary" type="submit">ยืนยันและเริ่มนับ 7 วัน</Button></div></form></Modal>;
}
