import React, {useState,useEffect} from 'react';
import {Button,DataComponent,DataTable,Dialog} from '../../data-app-public.jsx';
import {OFFERS,OBJECTIVES,PRIMARY,dayDiff,plusDays,measure,summary} from '../shared/model.mjs';
import {Field,Modal,fmt,pct,offerName} from './Forms.jsx';
import pairAnalysis from '../assets/metrics-pair-analysis_gen-d190a201.webp';
import pairChart from '../assets/metrics-pair-chart_gen-04ac9b83.webp';
import pairClipboard from '../assets/metrics-pair-clipboard_gen-80d72fb8.webp';

export const dateLabel=d=>d?new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'2-digit'}).format(new Date(d+'T00:00:00')):'ยังไม่กำหนด';
export const STATUS={HOLD_SCALE:'แก้ SLA ก่อนเพิ่มงบ',DATA_HOLD:'รอข้อมูลและข้อกำหนด',LEARNING:'กำลังเก็บหลักฐาน',BLOCK:'หยุดเพิ่มความเสี่ยง',FIX:'แก้จุดที่ติดก่อน',BASE:'พร้อมพิจารณา Base',HIGH:'พร้อมพิจารณา High',ON_TRACK:'ติดตามตามแผน'};
export const DEFINITIONS={
  units:['Net fulfilled units','ส่งมอบ − คืนสินค้า ตามวันที่เกิดแต่ละเหตุการณ์ ไม่รวมคำสั่งซื้อที่ยังไม่ส่ง','อยากรู้ว่าลด stock ได้จริงแค่ไหน ให้ดู units ที่ส่งมอบสุทธิ'],
  revenue:['Net revenue','ยอดชำระหลังส่วนลดตามวันซื้อ − เงินคืนตามวันคืนเงิน ไม่รวม void','ยอดขายดีแต่คืนเงินมาก ให้ดู net revenue แทนยอดสั่งซื้อ'],
  sql:['Sales-qualified leads','จำนวน lead ไม่ซ้ำที่เข้า SQL ในช่วงวันที่เลือก ตามเกณฑ์ที่เจ้าของแคมเปญกำหนด','มีคนทักเยอะ แต่พร้อมซื้อไหม ให้ดู SQL'],
  qualifiedVisits:['Qualified visits','Sessions ที่ผ่านนิยาม qualified ของแคมเปญ ไม่ใช่จำนวนคนไม่ซ้ำ','คนคลิกแล้วเข้าหน้าจริงและมีคุณภาพไหม ให้ดู qualified sessions'],
  spend:['Media spend','ผลรวมค่าโฆษณาของ observations ในช่วง / offer / channel ที่เลือก','ใช้งบเร็วกว่าแผนไหม ให้เทียบ spend + commitments กับ cap'],
  contribution:['Contribution after media','Net revenue − COGS − packaging − shipping − fees − commission − other − media ใช้ได้เมื่อต้นทุนครบ','ขายได้เยอะแล้วเหลือเท่าไร ให้ดู contribution; ยังไม่ใช่กำไรสุทธิ'],
  margin:['Contribution margin','Contribution after media ÷ net revenue; ไม่ประเมินเมื่อ net revenue ≤ 0','CVR สูงแต่ margin ต่ำกว่า floor ก็ยังไม่ควรเพิ่มงบ'],
  ctr:['Link CTR','Link clicks ÷ impressions ของ ad observations ใน scope เดียวกัน','อยากรู้ว่าคอนเทนต์ชวนคลิกไหม ให้ดู CTR แล้วดู lead quality ต่อ'],
  cvr:['Mature Lead-to-Sale','Lead ที่มี eligible order ภายใน conversion window ÷ leads ที่ครบ window แล้ว นับแต่ละ lead ครั้งเดียว','อยากรู้ว่าคนทักซื้อจริงไหม ให้ดู CVR ของ cohort ที่ครบเวลา'],
  cpl:['CPL','Media spend ÷ acquired leads ในช่วงเดียวกัน; ใช้ acquisition channel จาก CRM','ได้ lead แพงไหม ให้ดู CPL ควบคู่ MQL/SQL'],
  cpo:['CPO','Media spend ÷ eligible orders ที่ซื้อในช่วง ไม่ใช่ CAC ต่อคน','ต้นทุนสื่อต่อออเดอร์เท่าไร ให้ดู CPO'],
  mediaCAC:['Media CAC','Media spend ÷ distinct Customer IDs ที่ยืนยันเป็นลูกค้าใหม่ใน order cohort นี้ ไม่รวม acquisition cost อื่น','ลูกค้าคนเดิมซื้อซ้ำไม่ใช่ลูกค้าใหม่ ต้องมี Customer ID'],
  aov:['AOV · purchase cohort','ยอดชำระสุทธิถึงวัน review ของ eligible orders ที่ซื้อในช่วง ÷ order count ชุดเดียวกัน','แต่ละบิลมีมูลค่าเฉลี่ยเท่าไร ให้ดู AOV'],
  upo:['Units per order · purchase cohort','หน่วยส่งมอบสุทธิถึงวัน review ของ eligible orders ที่ซื้อในช่วง ÷ order count ชุดเดียวกัน','แพ็กคู่ช่วยจำนวนต่อบิลไหม ให้ดู UPO และ margin พร้อมกัน'],
  mql:['Marketing-qualified leads','Lead IDs ที่เข้า MQL ในช่วงนี้ อาจได้ lead มาก่อนช่วงนี้; ไม่บวก MQL และ SQL เป็นคนทั้งหมด','คอนเทนต์ดึงคนที่ตรงกลุ่มไหม ให้ดู MQL'],
  sla:['Response SLA','Leads ที่ตอบภายในนาทีที่กำหนด ÷ leads ที่ตอบแล้วหรือเข้ามาก่อนวัน review; same-day ยังไม่ตอบแยกรอข้อมูล','มีคนพร้อมซื้อแต่ตอบช้า ให้แก้ SLA ก่อนเพิ่มงบ'],
  leadCount:['Acquired leads','Lead IDs ไม่ซ้ำที่เข้ามาในช่วง acquisition date; channel และ offer ใช้ตอน acquisition','จำนวนคนทักเป็นเพียงจุดเริ่ม ดู MQL/SQL และยอดซื้อด้วย'],
  orders:['Eligible orders','Distinct order IDs ที่ชำระในช่วงและยังมีมูลค่าสุทธิ ณ วัน review; ยกเลิก/void ไม่รวม','ดูจำนวนออเดอร์แยกจากจำนวนองค์และจำนวนลูกค้า'],
};
export const metricFormat=(k,v)=>['ctr','cvr','margin','sla','responseCoverage'].includes(k)?pct(v):fmt(v,['aov','cpl','cpo','mediaCAC','upo','qualifiedCPL','sqlCPL'].includes(k)?2:0);
export function download(name,value,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Badge({children,tone='neutral'}){return <span className={`mc-badge ${tone}`}>{children}</span>;}
export function Empty({title,children,action}){return <div className="mc-empty"><span className="mc-empty-mark" aria-hidden="true">↗</span><strong>{title}</strong>{children&&<p>{children}</p>}{action}</div>;}
export function Panel({title,action,children,className=''}){return <section className={`mc-panel ${className}`}><header><h2>{title}</h2>{action}</header>{children}</section>;}
export function Companion({view}){const info={overview:[pairAnalysis,'อ่านตัวเลข แล้วเลือกสิ่งที่ต้องทำ','zuri ช่วยอ่านผล · น้องวางใจช่วยตรวจเงื่อนไข'],performance:[pairChart,'ดูจุดติดขัดทีละช่วง','เช่น CTR ดี แต่ SQL ต่ำ → ตรวจความตรงกลุ่มของ lead'],plan:[pairClipboard,'ครบสัปดาห์ = ถึงเวลาทบทวน','เปิดแพ็กเกจเมื่อมีหลักฐานและผ่านเงื่อนไข'],work:[pairClipboard,'ส่งงานแล้ว ต้องกลับมาตรวจผล','Done มีหลักฐาน · ผล KPI ติดตามในวัน recheck'],review:[pairAnalysis,'เก็บทั้งคำตัดสินและเหตุผล','เพื่อรู้ว่าเราเปลี่ยนอะไร และผลรอบต่อไปเป็นอย่างไร']}[view]||[];return <aside className={`mc-companion ${view}`}><img src={info[0]} alt="zuri และ น้องวางใจ ช่วยติดตามแคมเปญ"/><div><strong>{info[1]}</strong><p>{info[2]}</p></div></aside>;}
export function Metric({name,value,unit,caption,onClick,accent=false}){return <button type="button" className={`mc-metric ${accent?'accent':''}`} onClick={onClick}><span>{name}<span aria-hidden="true">↗</span></span><strong>{value}<small>{unit}</small></strong><p>{caption}</p></button>;}
export function PhaseRail({campaign,gate}){return <ol className="mc-phase-rail">{OFFERS.map((o,i)=>{const r=campaign.releases.find(r=>r.offer===o.id),active=gate.phase.offer===o.id;return <li key={o.id} className={active?'active':r||i===0?'started':''}><span className="mc-phase-dot">{String(i+1).padStart(2,'0')}</span><div><strong>{o.name}</strong><small>{i===0?`ขายปกติ · ${dateLabel(campaign.start)}`:r?`เปิดจริง ${dateLabel(r.date)}`:i===1?'แพ็กเกจ 1 · มีเงื่อนไข':'รอผลและคำตัดสิน'}</small></div>{active&&<Badge>ปัจจุบัน</Badge>}</li>})}</ol>;}
export function Evidence({id,title,rows,sourceRows,description,chart,children,headerControls}){return <DataComponent id={id} title={title} kind={chart?'chart':'custom'} queryId="manual_workspace" displayRows={rows} sourceRows={sourceRows||rows} description={description} chart={chart} variant="card" headerControls={headerControls}>{children}</DataComponent>;}
export function PeriodComparison({campaign,scope}){const days=dayDiff(scope.from,scope.to);if(days==null)return <p className="mc-note">กำหนดช่วงวันที่เพื่อเทียบช่วงก่อนหน้า</p>;const before={...scope,from:plusDays(scope.from,-days-1),to:plusDays(scope.from,-1)},a=measure(campaign,scope),b=before.from<campaign.start?null:measure(campaign,before);return <><p className="mc-note">ช่วงก่อน {dateLabel(before.from)} – {dateLabel(before.to)} · จำนวนวันเท่ากัน; phase หรือ mix อาจต่างกัน จึงไม่ยืนยันเหตุและผล</p><div className="mc-table-scroll"><table className="mc-compact-table"><thead><tr><th>Metric</th><th>ก่อน</th><th>ปัจจุบัน</th><th>Δ</th></tr></thead><tbody>{[[PRIMARY[campaign.objective][0],PRIMARY[campaign.objective][1]],['spend','Media spend'],['contribution','Contribution']].map(([key,label])=><tr key={key}><th>{label}</th><td>{metricFormat(key,b?.[key])}</td><td>{metricFormat(key,a[key])}</td><td>{a[key]!=null&&b?.[key]!=null?fmt(a[key]-b[key]):'—'}</td></tr>)}</tbody></table></div></>;}
export function Ledger({type,rows,onEdit}){const fields={ads:['date','offer','channel','spend','impressions','clicks'],leads:['date','offer','channel','mqlAt','sqlAt'],orders:['date','offer','status','amount','refund','fulfilled'],inventory:['date','sku','sellable','reserved','available']}[type];return rows.length?<DataTable caption={`Manual ${type} records`} rowKey="id" rows={rows} onRowSelect={onEdit} rowActionLabel={r=>`แก้ไข ${r.id}`} columns={[{field:'id',label:'Record ID'},...fields.map(field=>({field,label:field}))]}/>:<Empty title="ไม่มี record ใน scope นี้">บันทึกข้อมูลจริง หรือปรับตัวกรองเพื่อดูรายการอื่น</Empty>;}
export function Forecast({campaign,actual,onSave}){const [values,setValues]=useState(campaign.forecast||{});useEffect(()=>setValues(campaign.forecast||{}),[campaign.id,campaign.forecast]);const complete=OFFERS.every(o=>values[o.id]!=null),units=complete?OFFERS.reduce((s,o)=>s+values[o.id]*o.units,0):null,revenue=complete?OFFERS.reduce((s,o)=>s+values[o.id]*o.price,0):null;return <Panel title="Reforecast · ออเดอร์ที่คาดว่าจะขายเพิ่มจากวันนี้" action={<Button onClick={()=>onSave(values)} disabled={Object.values(values).some(v=>v!=null&&(!Number.isInteger(v)||v<0))}>บันทึก scenario</Button>}><div className="mc-forecast-grid">{OFFERS.map(o=><Field key={o.id} label={`${o.name} · ฿${fmt(o.price)}`} value={values[o.id]} type="number" min="0" onChange={v=>setValues(p=>({...p,[o.id]:v}))} hint={`${o.units} unit / order`}/>)}</div><div className="mc-forecast-results"><span>Future units<b>{fmt(units)}</b></span><span>Future revenue*<b>฿{fmt(revenue)}</b></span><span>Actual + future units<b>{units!=null&&actual.units!=null?fmt(units+actual.units):'—'}</b></span><span>Actual + future revenue*<b>{revenue!=null&&actual.revenue!=null?'฿'+fmt(revenue+actual.revenue):'—'}</b></span></div><p className="mc-note">กรอกครบทั้ง 4 ช่อง รวม 0 สำหรับ offer ที่ไม่เลือก · เป็น gross-price scenario ก่อนคืนเงิน/ส่วนลดเพิ่มเติม ไม่ใช่ forecast margin หรืองบอนุมัติ · Normal ฿5,900 ยังต้องยืนยันเงื่อนไขจริง</p></Panel>;}
export function NewCampaign({onSave,onClose}){const [name,setName]=useState(''),[objective,setObjective]=useState('inventory');return <Modal title="เพิ่มแคมเปญ" onClose={onClose} wide={false}><form onSubmit={e=>{e.preventDefault();if(name.trim())onSave(name.trim(),objective);}}><div className="mc-form-grid single"><Field label="ชื่อแคมเปญ" value={name} onChange={setName} required/><Field label="Objective" value={objective} options={Object.entries(OBJECTIVES).map(([value,label])=>({value,label}))} onChange={setObjective}/></div><div className="mc-form-actions"><Button className="mc-primary" type="submit">สร้างและตั้งเป้าหมาย</Button></div></form></Modal>;}
export function Acknowledge({alert,onSave,onClose}){const [owner,setOwner]=useState(alert.owner),[note,setNote]=useState(alert.note);return <Modal title={`รับทราบ ${alert.id}`} onClose={onClose} wide={false}><form onSubmit={e=>{e.preventDefault();if(owner.trim()&&note.trim())onSave({owner,note});}}><p>{alert.title}</p><div className="mc-form-grid single"><Field label="ผู้รับผิดชอบ" value={owner} onChange={setOwner} required/><Field label="สิ่งที่จะตรวจ / แนวทางแก้" type="textarea" value={note} onChange={setNote} required/></div><div className="mc-form-actions"><Button className="mc-primary" type="submit">รับทราบ</Button></div></form></Modal>;}
export function ReviewEditor({campaign,asOf,onSave,notify}){const [text,setText]=useState(()=>summary(campaign,asOf));return <Panel title="สรุปเพื่อ review" action={<Button onClick={()=>setText(summary(campaign,asOf))}>อัปเดตจากข้อมูล</Button>}><p className="mc-note">แก้คำอธิบายและสมมติฐานได้; ตัวเลขต้นทางแนบใน snapshot แยกจากข้อความ</p><label className="mc-review-text"><span className="mc-sr-only">Review summary</span><textarea value={text} onChange={e=>setText(e.target.value)}/></label><div className="mc-form-actions"><Button onClick={async()=>{try{await navigator.clipboard.writeText(text);notify('คัดลอก summary แล้ว');}catch{download(`review-${asOf}.txt`,text,'text/plain');notify('ดาวน์โหลดข้อความแทน clipboard');}}}>คัดลอก</Button><Button className="mc-primary" onClick={()=>onSave(text)}>บันทึก review snapshot</Button></div></Panel>;}
export function SnapshotDetail({kind,entry}){if(kind==='history')return <><p><b>v{entry.version-1} → v{entry.version}</b> · {entry.reason}</p><pre className="mc-json">{JSON.stringify(entry.previous,null,2)}</pre></>;const s=entry.snapshot;return <><p className="mc-preserve-lines">{entry.reason||entry.text}</p><dl className="mc-facts"><div><dt>วันหลักฐาน / Version</dt><dd>{s.asOf} / v{s.version}</dd></div><div><dt>Gate ณ เวลาบันทึก</dt><dd>{s.gate.status}</dd></div><div><dt>Net fulfilled units</dt><dd>{fmt(s.metrics.units)}</dd></div><div><dt>Net revenue / Media spend</dt><dd>{fmt(s.metrics.revenue)} / {fmt(s.metrics.spend)} บาท</dd></div><div><dt>Contribution</dt><dd>{fmt(s.metrics.contribution)} บาท</dd></div></dl><p className="mc-note">เก็บตามวันที่และเกณฑ์เดิม การแก้ records หรือ targets ปัจจุบันไม่เปลี่ยน snapshot นี้</p>{entry.evidence&&<p>หลักฐาน: {entry.evidence}</p>}{entry.priorOffers&&<p>Offer เดิม: {entry.priorOffers}</p>}</>;}
export function MetricDetail({campaign,detail,onClose,onTask}){const m=measure(campaign,detail.scope),def=DEFINITIONS[detail.key]||[detail.key,'ดู records ใน scope เดียวกัน',''];const rows=['ctr','spend','qualifiedVisits'].includes(detail.key)?m.ads:['cvr','leadCount','mql','sql','sla','cpl'].includes(detail.key)?[...new Map([...m.leads,...m.stageRows].map(r=>[r.id,r])).values()]:m.orderRows;return <Dialog open onClose={onClose} title={def[0]} className="mc-detail-dialog"><div className="mc-modal"><div className="mc-detail-value">{metricFormat(detail.key,m[detail.key])}</div><p>{def[1]}</p><p className="mc-example">{def[2]}</p><dl className="mc-facts"><div><dt>ช่วงวันที่</dt><dd>{detail.scope.from||'ทั้งหมด'} – {detail.scope.to}</dd></div><div><dt>Offer / channel</dt><dd>{offerName(detail.scope.offer)||'all'} / {detail.scope.channel||'all'}</dd></div><div><dt>Source</dt><dd>Manual records · provisional</dd></div><div><dt>Target / rule</dt><dd>v{campaign.version} · {PRIMARY[campaign.objective][1]}</dd></div></dl>{detail.key==='cvr'&&<p className="mc-note">Converted {m.converted} / mature {m.mature}; pending {m.pending} · window {fmt(campaign.windowDays)} วัน · link ข้าม offer ได้ตาม Lead ID</p>}<h3>Records ใน scope ({rows.length})</h3><div className="mc-table-scroll"><table><thead><tr><th>ID</th><th>วันที่</th><th>Offer</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th>{r.id}</th><td>{r.date}</td><td>{offerName(r.offer)}</td></tr>)}</tbody></table></div><h3>งานที่เกี่ยวข้อง</h3>{campaign.tasks.filter(t=>t.gate?.toLowerCase().includes(detail.key.toLowerCase())).map(t=><p key={t.id}>{t.title} · {t.status}</p>)}<Button className="mc-primary" onClick={onTask}>สร้างงานจากสิ่งที่พบ</Button></div></Dialog>;}

