import {useWriteAccess} from './TeamAccess.jsx';
import {ZuriGoLogo} from '../shared/ZuriGoLogo.jsx';
import React,{useEffect,useState,useRef} from 'react';
import {Button,DataComponent,useDataApp} from '../../data-app-public.jsx';
import {Field,Modal,fmt} from '../dashboard/Forms.jsx';
import {LIFECYCLE,APPROVAL,PUBLICATION,METRICS,localDate,periodFor,midnight,overview,summaryFacts,addDays} from './model.mjs';
import {request,scoped,modeKey} from './api.mjs';
import pairAnalysis from '../assets/metrics-pair-analysis_gen-d190a201.webp';
import pairChart from '../assets/metrics-pair-chart_gen-04ac9b83.webp';
import pairClipboard from '../assets/metrics-pair-clipboard_gen-80d72fb8.webp';
import './business.css';
const choices=obj=>Object.entries(obj).map(([value,label])=>({value,label}));
const time=value=>value?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(value)):'ยังไม่กำหนด';
const day=value=>value?new Date(value+'T12:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short'}):'—';
const localInput=value=>value?new Date(Date.parse(value)+7*3600000).toISOString().slice(0,16):'';
const stamp=value=>value?new Date(value+'+07:00').toISOString():null;
const emptyChoice={value:'',label:'ยังไม่ระบุ'};
function SourceBlock({id,title,rows,children,description}){return <DataComponent id={id} title={title} kind="custom" queryId="zuri_go_workspace" sourceRows={rows} displayRows={rows} description={description} variant="card">{children}</DataComponent>;}
function CheckList({label,items,selected,onChange}){return <fieldset className="zg-checks"><legend>{label}</legend>{items.length?items.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>onChange(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/>{x.display_name||x.source_label}</label>):<p>เพิ่มช่องทางก่อน</p>}</fieldset>;}
function GoalCard({goal,onRecord,onEdit}){return <div className="zg-goal"><div className="zg-row"><h3>{goal.name}</h3><button className="zg-text-button" onClick={()=>onEdit(goal)}>แก้เป้า</button></div><p>{day(goal.period_start)} – {day(addDays(goal.period_end_exclusive,-1))}</p><div className="zg-goal-value"><strong>{goal.actual===null?'—':fmt(goal.actual)}</strong><span>/ {fmt(goal.target_value)} {goal.metric_code==='net_revenue'?'บาท':goal.metric_code==='published_posts'?'รายการ':'ราย'}</span></div><div className="zg-progress" role="progressbar" aria-label={goal.name} aria-valuenow={goal.barPercent} aria-valuemin="0" aria-valuemax="100"><i style={{width:goal.barPercent+'%'}}/></div><div className="zg-row"><b>{goal.percent==null?'รอข้อมูล':fmt(goal.percent,1)+'%'}</b><span>{goal.remaining==null?'':goal.remaining===0?(goal.quality==='complete'?'ถึงเป้าแล้ว':'รอตรวจข้อมูลครบ'):'เหลือ '+fmt(goal.remaining)}</span></div>{goal.stock!=null&&<p>ผู้ติดตามสะสม {fmt(goal.stock)} บัญชี</p>}<small className={goal.quality==='complete'?'':'zg-warning'}>{goal.quality==='complete'?'ข้อมูลครบขอบเขต':goal.quality==='missing'?'ยังขาดข้อมูลต้นรอบหรือผลล่าสุด':goal.quality==='stale'?'ข้อมูลต้องอัปเดต':'ข้อมูลบางส่วน / เวลาแต่ละช่องทางไม่ตรงกัน'}</small><small>ข้อมูลถึง {time(goal.asOf)}</small>{goal.metric_code!=='published_posts'&&<Button onClick={()=>onRecord(goal)}>อัปเดตผลจริง ↗</Button>}<details><summary>วิธีนับและแหล่งข้อมูล</summary><p>{goal.metric_code==='followers_net'?'ยอดล่าสุด − ยอดต้นรอบ จากบัญชีชุดเดิม ผลรวมข้ามช่องทางไม่ใช่คนที่ไม่ซ้ำ':'ผลจริงเฉพาะช่วงและช่องทางที่เลือก'}</p>{goal.details.map((d,i)=><p key={i}>{d.label||'รายการเผยแพร่'} · {d.reason||fmt(d.value)} · {time(d.effectiveAt)}</p>)}</details></div>;}

export function BusinessWorkspace({view='overview',cloud=false,legacyCampaigns,legacyDomain,onActivateServer,onOpenCampaign,onOpenMeeting}){
 const shell=useDataApp(),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[modal,setModalState]=useState(null),[busy,setBusy]=useState(false),[date,setDate]=useState(localDate()),[kind,setKind]=useState('weekly'),[filter,setFilter]=useState('all'),[brief,setBrief]=useState(null),[importReport,setImportReport]=useState(null),[includeTranscript,setIncludeTranscript]=useState(false);
 const {requestWrite}=useWriteAccess();
 const setModal=value=>value?requestWrite(()=>setModalState(value)):setModalState(null);
 const generation=useRef(0),pendingFilter=useRef(null);const [businessId,setBusinessId]=useState(null);
 async function load(){const version=++generation.current;setLoading(true);setError('');try{const info=await request('/bootstrap'),value=await scoped(info.business.id,'/state');if(version!==generation.current)return;setBusinessId(info.business.id);setData(value);setBrief(null);}catch(e){if(version===generation.current)setError(e.message);}finally{if(version===generation.current)setLoading(false);}}
 useEffect(()=>{load();return()=>{generation.current++;};},[]);
 useEffect(()=>{setFilter(pendingFilter.current?.view===view?pendingFilter.current.value:'all');pendingFilter.current=null;},[view]);
 async function mutate(path,method,payload,message='บันทึกแล้ว'){setBusy(true);try{await scoped(businessId,path,method,payload);setModal(null);setNotice(message);await load();}catch(e){setError(e.message);throw e;}finally{setBusy(false);}}
 const result=data?overview(data,{date,kind}):null;
 function go(tab,value='all'){if(tab===view){setFilter(value);return;}pendingFilter.current={view:tab,value};shell.exploreDashboard(tab);}
 async function generateBrief(){setBusy(true);const token=++generation.current;const options={date,kind,asOf:result.asOf};try{const value=await scoped(businessId,'/briefs','POST',options);if(token===generation.current)setBrief({value,date,kind,revision:data.business.row_version});}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function previewImport(){setBusy(true);try{const namespace=localStorage.getItem('zuri-go:import-namespace')||crypto.randomUUID();localStorage.setItem('zuri-go:import-namespace',namespace);const backup={schemaVersion:2,appId:shell.snapshot.id,campaignWorkspace:legacyCampaigns,meetingTaskManager:legacyDomain};const value=await scoped(businessId,'/imports','POST',{backup,source_namespace:namespace,includeTranscript});setImportReport(value);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function commitImport(){setBusy(true);try{await scoped(businessId,`/imports/${importReport.id}/commit`,'POST',{backup_sha256:importReport.backup_sha256});localStorage.setItem(modeKey(shell.snapshot.id),businessId);onActivateServer(businessId);setImportReport(null);setModal(null);setNotice('นำเข้าสำเร็จ ตรวจยอดก่อนและหลังแล้ว ข้อมูล browser เดิมยังคงอยู่');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const memberChoices=data?[emptyChoice,...data.members.filter(m=>m.status==='active').map(m=>({value:m.id,label:m.display_name}))]:[];
 const campaignChoices=data?[{value:'',label:'ไม่ผูกแคมเปญ'},...data.campaigns.filter(c=>!c.archived_at).map(c=>({value:c.id,label:c.name}))]:[];
 const newGoal=period=>({kind:'goal',row:{name:'ผู้ติดตามเพิ่มสุทธิ',metric_code:'followers_net',period_kind:period,period_start:periodFor(date,period).start,target_value:null,series_ids:[]}});
 function renderForm(){if(!modal||modal.kind==='import')return null;return <BusinessForm key={modal.kind+(modal.row?.id||'new')} modal={modal} data={data} memberChoices={memberChoices} campaignChoices={campaignChoices} busy={busy} onClose={()=>setModal(null)} onSave={mutate}/>;}
 if(loading&&!data)return <section className="zg-app" aria-busy="true"><p>กำลังเปิดภาพรวมธุรกิจ…</p></section>;
 if(!data)return <section className="zg-app"><ZuriGoLogo/><div role="alert" className="mc-errors">{error}</div><Button onClick={load}>ลองเชื่อมต่ออีกครั้ง</Button>{!cloud&&<Button onClick={()=>onOpenCampaign(null,true)}>เปิดแคมเปญที่เก็บใน browser</Button>}</section>;
 const contentRows=data.content_items.filter(c=>!c.archived_at&&(filter==='all'?c.planning_month===date.slice(0,7)+'-01':filter==='review'?c.approval_status==='in_review':filter==='upcoming'?result.upcoming.some(p=>p.content_item_id===c.id):filter==='overdue'?result.overdue.some(p=>p.content_item_id===c.id):true));
 const campaignRows=result.campaigns.filter(c=>filter==='all'||c.lifecycle===filter);
 const activeBrief=brief&&brief.date===date&&brief.kind===kind?brief:null;
 const rules=summaryFacts(result).filter(x=>x.id!=='campaigns').slice(0,3);
 return <article className="zg-app" data-reviewed-rows>
  <header className="zg-header"><ZuriGoLogo/><div className="zg-business"><span>ธุรกิจ</span><button onClick={()=>setModal({kind:'business',row:data.business})}>{data.business.name} <span>✎</span></button><small>PostgreSQL · {cloud?'ของทีม':'ในเครื่องนี้'}</small></div></header>
  <div className="zg-toolbar"><div><h1>{view==='overview'?'ภาพรวมธุรกิจ':view==='campaigns'?'แคมเปญของธุรกิจ':view==='content'?'วางคอนเทนต์ให้พร้อมลง':'เป้าหมายและผลจริง'}</h1><p>{view==='overview'?'ทำอะไรอยู่ · ถึงเป้าแค่ไหน · ไปต่ออย่างไร':view==='content'?'หนึ่งชิ้นงาน ลงได้หลายช่องทาง':view==='goals'?'เห็นผลจริง เทียบเป้าที่ตั้งไว้':'เห็นทุกแคมเปญ แล้วเลือกเข้าไปดูรายละเอียด'}</p></div><div className="zg-toolbar-actions"><Field label="วันที่อ้างอิง" type="date" value={date} onChange={v=>{if(v){setDate(v);setBrief(null);}}}/>{view==='overview'&&<div className="zg-switch"><button aria-pressed={kind==='weekly'} onClick={()=>{setKind('weekly');setBrief(null);}}>สัปดาห์นี้</button><button aria-pressed={kind==='monthly'} onClick={()=>{setKind('monthly');setBrief(null);}}>เดือนนี้</button></div>}<Button className="mc-primary" onClick={()=>setModal(view==='content'?{kind:'content',row:{planning_month:date.slice(0,7)+'-01'}}:view==='goals'?newGoal('weekly'):{kind:'campaign',row:{lifecycle:'draft',objective:'awareness',channel_ids:[]}})}>＋ {view==='content'?'วางคอนเทนต์':view==='goals'?'ตั้งเป้าหมาย':'เพิ่มแคมเปญ'}</Button></div></div>
  {error&&<div className="mc-errors" role="alert">{error}<button className="zg-text-button" onClick={()=>setError('')}>ปิด</button></div>}{notice&&<p role="status" className="mc-notice">{notice}<button onClick={()=>setNotice('')}>×</button></p>}
  {!cloud&&!localStorage.getItem(modeKey(shell.snapshot.id))&&<div className="zg-onboard"><div><strong>นำงานเดิมมาต่อใน Zuri-Go</strong><p>ตรวจ {legacyCampaigns?.campaigns?.length||0} แคมเปญ และ {legacyDomain?.tasks?.length||0} งานจาก browser นี้ก่อนนำเข้า</p></div><Button onClick={()=>setModal({kind:'import'})} disabled={!legacyDomain}>ตรวจข้อมูลเดิม ↗</Button><button className="zg-text-button" onClick={()=>{localStorage.setItem(modeKey(shell.snapshot.id),businessId);onActivateServer(businessId);setNotice('เริ่ม workspace PostgreSQL แล้ว ข้อมูล browser เดิมยังเก็บไว้');}}>{data.campaigns.length?'ใช้ workspace PostgreSQL นี้':'เริ่ม workspace ว่าง'}</button></div>}
  {view==='overview'&&<>
   <section className="zg-stats" aria-label="สถานะการตลาด"><button onClick={()=>go('campaigns','active')}><span>กำลังรัน</span><strong>{fmt(result.counts.active)}<small>แคมเปญ</small></strong><em>ดูแคมเปญ ↗</em></button><button onClick={()=>go('campaigns','queued')}><span>อยู่ในคิว</span><strong>{fmt(result.counts.queued)}<small>แคมเปญ</small></strong><em>เตรียมให้พร้อม ↗</em></button><button onClick={()=>go('content','upcoming')}><span>รอลงตามตาราง · {kind==='weekly'?'สัปดาห์นี้':'เดือนนี้'}</span><strong>{fmt(result.counts.scheduled)}<small>รายการ</small></strong><em>จาก {result.counts.scheduledContents} ชิ้นงาน ↗</em></button><button onClick={()=>go('content')}><span>คอนเทนต์ในแผน · {new Date(date+'T12:00:00').toLocaleDateString('th-TH',{month:'long'})}</span><strong>{fmt(result.counts.contentMonth)}<small>ชิ้นงาน</small></strong><em>ลงแล้วอย่างน้อยหนึ่งช่องทาง {result.counts.publishedContents} ชิ้น ↗</em></button></section>
   <SourceBlock id="zgo-goals" title="เป้าที่เรากำลังไปด้วยกัน" rows={result.goals} description="เป้ารายสัปดาห์และเดือนแยกกัน ผู้ติดตามเพิ่มสุทธิ = ยอดล่าสุด − ยอดต้นรอบ; ข้อมูลขาดไม่ใช่ศูนย์"><div className="zg-goal-columns">{['weekly','monthly'].map(period=><section key={period}><div className="zg-row"><h2>{period==='weekly'?'Weekly goal':'Monthly goal'}</h2><button className="zg-text-button" onClick={()=>setModal(newGoal(period))}>＋ ตั้งเป้า</button></div>{result.goals.filter(g=>g.period_kind===period).length?result.goals.filter(g=>g.period_kind===period).map(g=><GoalCard key={g.id} goal={g} onEdit={row=>setModal({kind:'goal',row})} onRecord={goal=>setModal({kind:'observation',row:{goal_id:goal.id,series_id:goal.details[0]?.seriesId||''}})}/>):<div className="zg-empty-goal"><span>เริ่มจากเป้าเล็ก ๆ ที่วัดได้</span><p>{period==='weekly'?'เช่น ผู้ติดตามเพิ่มสุทธิ 500 คน':'ตั้งเป้าเดือนนี้แยกจากเป้ารายสัปดาห์'}</p><Button onClick={()=>setModal(newGoal(period))}>ตั้งเป้า{period==='weekly'?'สัปดาห์นี้':'เดือนนี้'} ↗</Button></div>}</section>)}</div></SourceBlock>
   <section className="zg-brief"><img src={pairAnalysis} alt="Zuri ช่วยสรุป และน้องวางใจช่วยตรวจสัญญาณ"/><div><div className="zg-row"><h2>Zuri สรุปให้</h2><span className="zg-chip">{activeBrief?.value.mode==='ai'?'AI · โมเดลในเครื่อง':'สรุปจากกติกา'}</span></div><ul>{(activeBrief?.value.summary||rules.length&&rules||[{id:'start',text:'เริ่มจากเพิ่มแคมเปญ วางคอนเทนต์ หรือตั้งเป้าแรกของธุรกิจ',action:'campaigns'}]).map(f=><li key={f.id}><button onClick={()=>go(f.action)}>{f.text} ↗</button></li>)}</ul>{activeBrief&&<small>{time(activeBrief.value.as_of)}{activeBrief.revision!==data.business.row_version?' · ข้อมูลเปลี่ยนแล้ว กรุณาสรุปใหม่':''}</small>}<Button disabled={busy} onClick={()=>requestWrite(generateBrief)}>{busy?'กำลังสรุป…':'สรุปข้อมูลล่าสุด'}</Button>{activeBrief&&<details><summary>ดูหลักฐานที่ใช้สรุป</summary><p>ข้อมูลถึง {time(activeBrief.value.as_of)}</p>{activeBrief.value.summary.map(f=><p key={f.id}>{f.id}: {f.text}</p>)}</details>}</div></section>
   <div className="zg-columns"><section className="zg-panel"><div className="zg-row"><h2>วันนี้ควรทำ</h2><span className="zg-chip">น้องวางใจชี้สัญญาณ</span></div>{[[result.overdue.length,'รายการเลยเวลาลง','content','overdue'],[result.pending.length,'ชิ้นรอตรวจคอนเทนต์','content','review'],[result.counts.unconfirmed,'แคมเปญรอยืนยันสถานะ','campaigns','unconfirmed'],[result.taskAttention.length,'งานเลยกำหนด / ติดขัด','meeting-task-manager','all']].filter(x=>x[0]>0).map(([n,label,tab,f])=><button className="zg-attention" key={label} onClick={()=>tab==='meeting-task-manager'?onOpenMeeting():go(tab,f)}><b>{n}</b><span>{label}</span><span>↗</span></button>)}{!result.overdue.length&&!result.pending.length&&!result.counts.unconfirmed&&!result.taskAttention.length&&<p className="zg-empty">ยังไม่มีรายการเร่งด่วนจากข้อมูลที่บันทึก</p>}</section><section className="zg-panel"><div className="zg-row"><h2>กำลังจะลง</h2><button className="zg-text-button" onClick={()=>go('content','upcoming')}>ดูตาราง ↗</button></div>{result.upcoming.slice(0,5).map(p=><button className="zg-upcoming" key={p.id} onClick={()=>setModal({kind:'publication',row:p})}><span>{time(p.scheduled_at)}</span><strong>{data.content_items.find(c=>c.id===p.content_item_id)?.title}</strong><small>{data.channel_accounts.find(a=>a.id===p.channel_account_id)?.display_name}</small></button>)}{!result.upcoming.length&&<div className="zg-empty"><p>คิวยังว่าง วางคอนเทนต์แรกได้เลย</p><Button onClick={()=>go('content')}>วางคอนเทนต์ ↗</Button></div>}</section></div>
  </>}
  {(view==='campaigns'||view==='overview')&&<SourceBlock id="zgo-campaigns" title="แคมเปญของธุรกิจ" rows={campaignRows} description="สถานะที่ผู้ใช้ยืนยัน ไม่เดาจากวันที่; ไม่รวม archived"><div className="zg-row"><p>ทุกแคมเปญใน {data.business.name}</p>{view==='campaigns'&&<Field label="กรองสถานะแคมเปญ" value={filter} options={[{value:'all',label:'ทุกสถานะ'},...choices(LIFECYCLE)]} onChange={setFilter}/>}</div>{!campaignRows.length?<p className="zg-empty">ยังไม่มีแคมเปญในขอบเขตนี้</p>:<div className="zg-table-wrap"><table><thead><tr><th>แคมเปญ</th><th>สถานะ</th><th>ช่วงเวลา</th><th>ผู้ดูแล</th><th>ไปต่อ</th></tr></thead><tbody>{campaignRows.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.code}</small></td><td><span className={'zg-state '+c.lifecycle}>{LIFECYCLE[c.lifecycle]}</span></td><td>{day(c.planned_start)} – {day(c.planned_end)}</td><td>{data.members.find(m=>m.id===c.owner_member_id)?.display_name||'ยังไม่ระบุ'}</td><td><button className="zg-text-button" onClick={()=>setModal({kind:'campaign',row:{...c,channel_ids:data.campaign_channels.filter(x=>x.campaign_id===c.id).map(x=>x.channel_account_id)}})}>จัดการ</button><button className="zg-text-button" onClick={()=>{localStorage.setItem(modeKey(shell.snapshot.id),businessId);onOpenCampaign(c.id,false,businessId);}}>เปิดแคมเปญ ↗</button></td></tr>)}</tbody></table></div>}</SourceBlock>}
  {view==='content'&&<><section className="zg-calendar zg-panel" aria-label="ตารางคอนเทนต์รายสัปดาห์"><div className="zg-row"><h2>ตารางสัปดาห์ · {day(periodFor(date).start)} – {day(addDays(periodFor(date).end,-1))}</h2><small>กดรายการเพื่อแก้เวลา / ยืนยันการลง</small></div><div className="zg-calendar-days">{Array.from({length:7},(_,i)=>addDays(periodFor(date).start,i)).map(d=><section key={d}><h3>{day(d)}</h3>{data.publications.filter(p=>p.status!=='cancelled'&&(p.published_at||p.scheduled_at)&&localDate(p.published_at||p.scheduled_at)===d).map(p=><button key={p.id} onClick={()=>setModal({kind:'publication',row:p})}><strong>{data.content_items.find(c=>c.id===p.content_item_id)?.title}</strong><small>{PUBLICATION[p.status]} · {data.channel_accounts.find(a=>a.id===p.channel_account_id)?.display_name}</small></button>)}</section>)}</div></section><section className="zg-channel-bar"><div><b>ช่องทางของธุรกิจ</b><span>{data.channel_accounts.map(a=>a.display_name).join(' · ')||'ยังไม่มีช่องทาง'}</span></div><Button onClick={()=>setModal({kind:'channel',row:{platform:'facebook'}})}>＋ เพิ่มช่องทาง</Button></section><div className="zg-row"><Field label="กรองคอนเทนต์" value={filter} options={[{value:'all',label:'แผนเดือนนี้'},{value:'review',label:'รอตรวจ'},{value:'upcoming',label:'รอลงตามช่วงที่เลือก'},{value:'overdue',label:'เลยเวลาลง'}]} onChange={setFilter}/><span>{contentRows.length} ชิ้นงาน · นับชิ้นเดียวแม้ลงหลายช่องทาง</span></div><div className="zg-content-grid">{contentRows.map(c=><section className="zg-content" key={c.id}><div className="zg-row"><span className="zg-chip">{APPROVAL[c.approval_status]}</span><small>{c.code}</small></div><h2>{c.title}</h2><p>{c.description||'เติมรายละเอียดภายหลังได้'}</p><small>{data.campaigns.find(x=>x.id===c.campaign_id)?.name||'คอนเทนต์ของธุรกิจ'} · {data.members.find(m=>m.id===c.owner_member_id)?.display_name||'ยังไม่มีผู้ดูแล'}</small><div className="zg-row"><Button onClick={()=>setModal({kind:'content',row:c})}>แก้ไข / ตรวจงาน</Button><Button onClick={()=>setModal({kind:'publication',row:{content_item_id:c.id,status:'draft',idempotency_key:crypto.randomUUID()}})}>＋ จัดตาราง</Button></div>{data.publications.filter(p=>p.content_item_id===c.id).sort((a,b)=>(a.scheduled_at||'').localeCompare(b.scheduled_at||'')).map(p=><button className="zg-publication" key={p.id} onClick={()=>setModal({kind:'publication',row:p})}><span>{data.channel_accounts.find(a=>a.id===p.channel_account_id)?.display_name}</span><b>{PUBLICATION[p.status]}</b><small>{time(p.published_at||p.scheduled_at)}</small></button>)}</section>)}</div>{!contentRows.length&&<div className="zg-empty"><p>ยังไม่มีคอนเทนต์ในรายการนี้</p><Button onClick={()=>setModal({kind:'content',row:{planning_month:date.slice(0,7)+'-01'}})}>วางคอนเทนต์แรก</Button></div>}</>}
  {view==='goals'&&<><section className="zg-channel-bar"><div><b>ช่องทางที่วัดผล</b><span>{data.channel_accounts.map(a=>a.display_name).join(' · ')||'เพิ่มบัญชีหรือเพจก่อนตั้งเป้า'}</span></div><Button onClick={()=>setModal({kind:'channel',row:{platform:'facebook'}})}>＋ เพิ่มช่องทาง</Button></section><div className="zg-goals-grid">{result.goals.map(g=><GoalCard key={g.id} goal={g} onEdit={row=>setModal({kind:'goal',row})} onRecord={goal=>setModal({kind:'observation',row:{series_id:goal.details[0]?.seriesId||''}})}/>)}</div>{!result.goals.length&&<p className="zg-empty">ยังไม่มีเป้าในช่วงนี้ ตั้งเป้ารายสัปดาห์หรือรายเดือนเพื่อเริ่มติดตาม</p>}<div className="zg-row"><Button onClick={()=>setModal(newGoal('weekly'))}>＋ Weekly goal</Button><Button onClick={()=>setModal(newGoal('monthly'))}>＋ Monthly goal</Button><Button onClick={()=>setModal({kind:'observation',row:{}})}>อัปเดตผลจริง</Button></div><details className="zg-panel"><summary>ประวัติข้อมูลจริงและการแก้ไข</summary>{data.metric_observations.filter(o=>o.is_current).sort((a,b)=>b.effective_at.localeCompare(a.effective_at)).slice(0,40).map(o=><button className="zg-publication" key={o.id} onClick={()=>setModal({kind:'observation',row:o})}><span>{data.metric_series.find(s=>s.id===o.series_id)?.source_label} · {data.metric_series.find(s=>s.id===o.series_id)?.metric_code}</span><b>{fmt(o.value)}</b><small>{time(o.effective_at)} · {o.source_ref}</small></button>)}</details></>}
  {view!=='overview'&&<footer className="zg-companion"><img src={view==='content'?pairClipboard:pairChart} alt="Zuri และน้องวางใจช่วยวางแผนและตรวจผลการตลาด"/><div><strong>{view==='content'?'วางแผนวันนี้ ให้วันลงงานเบาขึ้น':'เป้าที่ชัด ช่วยให้ไปต่อได้ง่าย'}</strong><p>Marketing made simple · ไปด้วยกันทีละก้าว</p></div></footer>}
  {renderForm()}
  {modal?.kind==='import'&&<Modal title="ตรวจข้อมูลเดิมก่อนนำเข้า PostgreSQL" onClose={()=>{setModal(null);setImportReport(null);}}><p>อ่านข้อมูลจาก browser นี้และนำเข้าฐานข้อมูลในเครื่อง ข้อมูลต้นฉบับยังเก็บไว้</p>{legacyDomain?.sources?.length>0&&<label><input type="checkbox" checked={includeTranscript} onChange={e=>setIncludeTranscript(e.target.checked)}/> รวม transcript และหลักฐานประชุม {legacyDomain.sources.length} ฉบับ</label>}{importReport?<><p>{importReport.campaigns} แคมเปญ · {importReport.tasks} งาน · {importReport.members} สมาชิก · {importReport.meetings} ประชุม</p><ul>{importReport.warnings.map(w=><li key={w}>{w}</li>)}</ul><Button className="mc-primary" disabled={busy||!importReport.canCommit} onClick={commitImport}>ยืนยันนำเข้าชุดนี้</Button></>:<Button disabled={busy} onClick={previewImport}>ตรวจรายการและความสัมพันธ์</Button>}</Modal>}
 </article>;
}

function BusinessForm({modal,data,memberChoices,campaignChoices,busy,onClose,onSave}){
 const {kind,row={}}=modal,[draft,setDraft]=useState(()=>{const d={...row};if(kind==='goal')d.series_ids=row.series_ids||data.goal_series.filter(x=>x.goal_id===row.id).map(x=>x.series_id);if(kind==='observation'){d.effective_at=localInput(row.effective_at||new Date().toISOString());d.date=row.period_start?localDate(row.period_start):localDate();}if(kind==='publication'){d.scheduled_at=localInput(row.scheduled_at);d.published_at=localInput(row.published_at);d.idempotency_key||=crypto.randomUUID();}return d;}),[error,setError]=useState('');
 const set=(k,v)=>setDraft(d=>({...d,[k]:v,...(k==='metric_code'?{series_ids:[]}:{} )}));
 const f=(key,label,type='text',options,hint)=><Field disabled={!!row.id&&kind==='campaign'&&key==='objective'} label={label} type={type} value={draft[key]} onChange={v=>set(key,v)} options={options} hint={hint}/>;
 const cfg={campaign:['แคมเปญ','campaigns','name objective lifecycle owner_member_id planned_start planned_end actual_started_at actual_ended_at channel_ids'],channel:['ช่องทาง','channels','platform display_name external_account_id url'],content:['คอนเทนต์','content','title description format planning_month campaign_id owner_member_id approval_status asset_url'],publication:['ตารางลงคอนเทนต์','publications','content_item_id channel_account_id status scheduled_at published_at published_url confirmation_note failure_reason idempotency_key'],goal:['เป้าหมาย','goals','name metric_code campaign_id owner_member_id period_kind period_start period_end_exclusive target_value status change_reason series_ids'],observation:['ผลจริง','observations','series_id value effective_at date source_ref correction_reason expected_id coverage'],business:['ชื่อธุรกิจ','','name']}[kind];
 async function submit(e){e.preventDefault();setError('');try{let payload={};for(const key of cfg[2].split(' '))if(draft[key]!==undefined)payload[key]=draft[key];if(row.id&&kind!=='observation')payload.row_version=row.row_version;
   if(kind==='goal'){const period=periodFor(draft.period_start,draft.period_kind);payload.period_start=period.start;payload.period_end_exclusive=period.end;payload.status=draft.status||'active';}
   if(kind==='content')payload.planning_month=draft.planning_month.slice(0,7)+'-01';
   if(kind==='publication'){payload.scheduled_at=stamp(draft.scheduled_at);payload.published_at=stamp(draft.published_at);}
   if(kind==='observation'){const series=data.metric_series.find(s=>s.id===draft.series_id);payload.effective_at=series?.metric_code==='followers_total'?stamp(draft.effective_at):midnight(addDays(draft.date,1),data.business.timezone);if(row.id)payload.expected_id=row.id;}
   const path=kind==='business'?'':`/${cfg[1]}${row.id&&kind!=='observation'?'/'+row.id:''}`;await onSave(path,kind==='business'||row.id&&kind!=='observation'?'PATCH':'POST',payload);
 }catch(e){setError(e.message);}}
 const selectedSeries=data.metric_series.find(s=>s.id===draft.series_id),seriesMetric=draft.metric_code==='followers_net'?'followers_total':draft.metric_code;
 return <Modal title={(row.id?'แก้ไข':'เพิ่ม')+cfg[0]} onClose={onClose}><form onSubmit={submit}>{error&&<p className="mc-errors" role="alert">{error}</p>}<div className="mc-form-grid">
  {kind==='business'&&f('name','ชื่อธุรกิจ')}
  {kind==='channel'&&<>{f('display_name','ชื่อเพจ / บัญชี')}{f('platform','แพลตฟอร์ม','text',choices({facebook:'Facebook',instagram:'Instagram',tiktok:'TikTok',line:'LINE',website:'Website',other:'อื่น ๆ'}))}{f('url','ลิงก์เพจ / บัญชี','url')}{f('external_account_id','Account ID (ถ้ามี)')}</>}
  {kind==='campaign'&&<>{f('name','ชื่อแคมเปญ')}{f('objective','ผลลัพธ์ที่ต้องการ','text',choices({awareness:'การรับรู้ / ผู้สนใจ',leads:'เก็บ leads',commerce:'ยอดขาย',inventory:'ระบายสินค้า'}))}{f('lifecycle','สถานะแคมเปญ','text',choices(LIFECYCLE))}{f('planned_start','วันเริ่มตามแผน','date')}{f('planned_end','วันสิ้นสุดตามแผน','date')}{f('owner_member_id','ผู้ดูแล','text',memberChoices)}<CheckList label="ช่องทางแคมเปญ" items={data.channel_accounts} selected={draft.channel_ids||[]} onChange={v=>set('channel_ids',v)}/></>}
  {kind==='content'&&<>{f('title','ชื่อคอนเทนต์')}{f('description','รายละเอียด','textarea')}{f('planning_month','เดือนในแผน','date',undefined,'เลือกวันที่ใดก็ได้ในเดือน ระบบจะเก็บเป็นเดือนเดียวกัน')}{f('format','รูปแบบ','text',[emptyChoice,...choices({image:'ภาพ',video:'วิดีโอ',carousel:'Carousel',text:'ข้อความ',other:'อื่น ๆ'})])}{f('campaign_id','แคมเปญ','text',campaignChoices)}{f('owner_member_id','ผู้ดูแล','text',memberChoices)}{f('approval_status','สถานะงาน','text',choices(APPROVAL))}{f('asset_url','ลิงก์ไฟล์งาน','url')}<p className="mc-note">การแก้เนื้อหาที่อนุมัติแล้วต้องตรวจใหม่ก่อนจัดตาราง</p></>}
  {kind==='publication'&&<>{f('content_item_id','ชิ้นคอนเทนต์','text',[emptyChoice,...data.content_items.filter(c=>!c.archived_at).map(c=>({value:c.id,label:c.title}))])}{f('channel_account_id','ช่องทางที่จะลง','text',[emptyChoice,...data.channel_accounts.map(a=>({value:a.id,label:a.display_name}))])}{f('status','สถานะการลง','text',choices(PUBLICATION))}{f('scheduled_at','กำหนดลง (เวลาไทย)','datetime-local')}{f('published_at','เวลาที่ลงจริง (ถ้าลงแล้ว)','datetime-local')}{f('published_url','ลิงก์โพสต์จริง','url')}{f('confirmation_note','หลักฐาน / หมายเหตุการลง','textarea')}{f('failure_reason','ปัญหาที่พบ','textarea')}<p className="mc-note">ตารางนี้เป็นแผน ระบบไม่โพสต์ลง social อัตโนมัติ</p></>}
  {kind==='goal'&&<>{f('name','ชื่อเป้าหมาย')}{f('metric_code','วัดอะไร','text',choices(METRICS))}{f('period_kind','รอบเป้า','text',[{value:'weekly',label:'รายสัปดาห์'},{value:'monthly',label:'รายเดือน'}])}{f('period_start','วันที่ในรอบเป้า','date')}{f('target_value','เป้าหมาย','number')}{f('owner_member_id','ผู้ดูแล','text',memberChoices)}<CheckList label="ช่องทางที่ใช้วัดเป้า" items={data.metric_series.filter(s=>s.metric_code===seriesMetric&&!s.campaign_id).map(s=>({...s,display_name:data.channel_accounts.find(a=>a.id===s.channel_account_id)?.display_name||s.source_label}))} selected={draft.series_ids||[]} onChange={v=>set('series_ids',v)}/>{row.id&&f('change_reason','เหตุผลที่แก้เป้า','textarea')}<p className="mc-note">ผู้ติดตามเพิ่มสุทธิ = ยอดล่าสุด − ยอดต้นรอบ ไม่รวมยอดสะสมเป็นผู้ติดตามใหม่</p></>}
  {kind==='observation'&&<>{f('series_id','ข้อมูลช่องทาง','text',[emptyChoice,...data.metric_series.filter(s=>s.source_kind==='manual'||s.source_kind==='import').map(s=>({value:s.id,label:(data.channel_accounts.find(a=>a.id===s.channel_account_id)?.display_name||s.source_label)+' · '+METRICS[s.metric_code]}))])}{f('value',selectedSeries?.metric_code==='followers_total'?'ยอดผู้ติดตามสะสม ณ เวลานั้น':'ผลจริงของวัน','number')}{selectedSeries?.metric_code==='followers_total'?f('effective_at','เวลาของยอดนี้ (เวลาไทย)','datetime-local',undefined,'ยอดต้นรอบให้ใช้วันจันทร์ 00:00 หรือวันที่ 1 เวลา 00:00 ตามหลักฐาน'):f('date','วันที่เกิดผลจริง','date')}{f('source_ref','ที่มาของตัวเลข / หลักฐาน')}{row.id&&f('correction_reason','เหตุผลที่แก้ตัวเลข','textarea')}{f('coverage','ความครบของข้อมูล','text',[{value:'complete',label:'ตรวจครบแล้ว'},{value:'partial',label:'ข้อมูลบางส่วน'}])}</>}
 </div><div className="mc-form-actions"><Button onClick={onClose}>ยกเลิก</Button><Button className="mc-primary" type="submit" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึก'}</Button></div></form></Modal>;
}
