import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {pool,transaction} from '../db.mjs';
import {OPERATOR} from '../viewer.mjs';
import {save,observe,snapshot,brief,hash} from '../service.mjs';
import {readLegacy,saveLegacy,importPreview,importCommit} from '../workspace.mjs';
import {empty,seedWorkspace,addSource,saveReview,addBatch,commitBatch,saveTask,validateState} from '../../web/src/content/meeting/model.mjs';
import {createWorkspace,measure} from '../../web/src/content/shared/model.mjs';
import {goalProgress,midnight} from '../../web/src/content/business/model.mjs';
const seed=JSON.parse(await readFile(new URL('../../web/src/content/meeting/seed.json',import.meta.url),'utf8'));
async function business(){const id=randomUUID();await transaction(id,c=>c.query('INSERT INTO businesses(id,name,slug) VALUES($1,$2,$3)',[id,'QA ONLY · isolated verification',id]));return id;}
// Service calls run as the trusted local operator, who sees the whole local database (FR-011-003 AC-04).
const run=(b,fn)=>transaction(b,OPERATOR,fn);
after(()=>pool.end());
test('actual PostgreSQL permissions, RLS, FK and RACI uniqueness',async()=>{
 const a=await business(),b=await business();
 const m=await run(a,c=>save(c,a,'members',{display_name:'QA A'})),n=await run(b,c=>save(c,b,'members',{display_name:'QA B'}));
 assert.equal((await run(a,c=>c.query('SELECT * FROM members WHERE id=$1',[n.id]))).rowCount,0);
 await assert.rejects(run(a,c=>c.query('INSERT INTO members(business_id,display_name) VALUES($1,$2)',[b,'Blocked'])),e=>e.code==='42501'||(e.code==='23514'&&e.message==='Business scope required'));
 assert.equal((await run(b,c=>c.query("SELECT id FROM members WHERE display_name='Blocked'"))).rowCount,0);
 await assert.rejects(run(a,c=>save(c,a,'campaigns',{name:'Cross business',owner_member_id:n.id})),e=>e.code==='23503');
 const role=(await run(a,c=>c.query('SELECT rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user'))).rows[0];assert.deepEqual(role,{rolsuper:false,rolbypassrls:false});
 const other=await run(a,c=>save(c,a,'members',{display_name:'QA second'}));
 const task=(await run(a,c=>c.query("INSERT INTO tasks(business_id,code,title) VALUES($1,'TEST-RACI','QA task') RETURNING *",[a]))).rows[0];
 await run(a,c=>c.query("INSERT INTO task_roles(business_id,task_id,member_id,role) VALUES($1,$2,$3,'R')",[a,task.id,m.id]));
 await assert.rejects(run(a,c=>c.query("INSERT INTO task_roles(business_id,task_id,member_id,role) VALUES($1,$2,$3,'R')",[a,task.id,other.id])),e=>e.code==='23505');
 await assert.rejects(run(a,c=>c.query("UPDATE metric_definitions SET label_th='blocked' WHERE code='leads'")),e=>e.code==='42501');
});
test('approval, scheduling, publication evidence and correction version conflicts',async()=>{
 const b=await business(),channel=await run(b,c=>save(c,b,'channels',{platform:'facebook',display_name:'QA page'}));
 const campaign=await run(b,c=>save(c,b,'campaigns',{name:'QA campaign',lifecycle:'active',channel_ids:[channel.id]}));assert.ok(campaign.actual_started_at);
 let content=await run(b,c=>save(c,b,'content',{title:'QA content',planning_month:'2026-09-01',campaign_id:campaign.id}));
 const input={content_item_id:content.id,channel_account_id:channel.id,status:'scheduled',scheduled_at:'2026-10-01T00:00:00.000Z',idempotency_key:randomUUID()};
 await assert.rejects(run(b,c=>save(c,b,'publications',input)),/อนุมัติ/);
 content=await run(b,c=>save(c,b,'content',{row_version:content.row_version,approval_status:'approved'},content.id));
 const pub=await run(b,c=>save(c,b,'publications',input));assert.equal((await run(b,c=>save(c,b,'publications',input))).id,pub.id);
 await assert.rejects(run(b,c=>save(c,b,'publications',{...input,scheduled_at:'2026-10-02T00:00:00Z'})),e=>e.status===409);
 const edited=await run(b,c=>save(c,b,'content',{row_version:content.row_version,title:'Changed content'},content.id));assert.equal(edited.approval_status,'draft');
 assert.equal((await run(b,c=>snapshot(c,b))).publications[0].status,'draft');
 await assert.rejects(run(b,c=>save(c,b,'content',{row_version:content.row_version,title:'Stale edit'},content.id)),e=>e.status===409);
 const p=(await run(b,c=>snapshot(c,b))).publications[0];
 await assert.rejects(run(b,c=>save(c,b,'publications',{row_version:p.row_version,status:'published',published_at:'2026-09-20T00:00:00Z'},p.id)),e=>e.code==='23514');
 await run(b,c=>save(c,b,'publications',{row_version:p.row_version,status:'published',published_at:'2026-09-20T00:00:00Z',confirmation_note:'QA evidence only'},p.id));
});
test('real stored observations produce net 320/500, corrections retain history, briefs are immutable and repeatable',async()=>{
 const b=await business(),channel=await run(b,c=>save(c,b,'channels',{platform:'facebook',display_name:'QA followers'})),s=(await run(b,c=>snapshot(c,b))).metric_series.find(x=>x.metric_code==='followers_total');
 const g=await run(b,c=>save(c,b,'goals',{name:'QA weekly',metric_code:'followers_net',period_kind:'weekly',period_start:'2026-09-21',period_end_exclusive:'2026-09-28',target_value:500,series_ids:[s.id]}));
 const input={series_id:s.id,effective_at:midnight('2026-09-21'),value:1000,source_ref:'QA fixture'};await run(b,c=>observe(c,b,input));
 const last=await run(b,c=>observe(c,b,{...input,effective_at:midnight('2026-09-23'),value:1320}));
 let data=await run(b,c=>snapshot(c,b));assert.equal(goalProgress(g,data,midnight('2026-09-23')).actual,320);
 await assert.rejects(run(b,c=>observe(c,b,{...input,value:-1})),/ไม่ถูกต้อง/);
 await assert.rejects(run(b,c=>observe(c,b,{...input,effective_at:last.effective_at,value:1330})),e=>e.status===409);
 await run(b,c=>observe(c,b,{...input,effective_at:last.effective_at,value:1330,expected_id:last.id,correction_reason:'QA correction'}));
 data=await run(b,c=>snapshot(c,b));assert.equal(data.metric_observations.length,3);assert.equal(data.metric_observations.filter(x=>x.is_current).length,2);assert.equal(goalProgress(g,data,midnight('2026-09-23')).actual,330);
 const options={date:'2026-09-23',kind:'weekly',asOf:midnight('2026-09-23')},first=await run(b,c=>brief(c,b,options)),again=await run(b,c=>brief(c,b,options));assert.equal(first.id,again.id);assert.equal(first.mode,'rule_based');assert.ok(first.summary.some(f=>f.text.includes('330')));
 await assert.rejects(run(b,c=>c.query("UPDATE ai_briefs SET summary='[]' WHERE business_id=$1",[b])),e=>e.code==='42501');
 await assert.rejects(run(b,c=>save(c,b,'goals',{name:'Bad dates',metric_code:'followers_net',period_kind:'weekly',period_start:'2026-09-22',period_end_exclusive:'2026-09-29',target_value:500,series_ids:[s.id]})),e=>e.code==='23514');
});
test('legacy preview/import/retry preserves campaign totals, task identity, RACI, MoSCoW and meeting evidence',async()=>{
 const b=await business(),ws=createWorkspace(),domain=empty();seedWorkspace(domain,seed);
 const campaign=ws.campaigns[0];campaign.tasks.push({id:'legacy-task',title:'QA campaign task',status:'Backlog',owner:'Chef'});
 campaign.ads.push({id:'a1',date:'2026-09-20',offer:'normal',channel:'Meta',spend:123,impressions:1000,clicks:10,qualifiedVisits:5});
 const src={sourceInstanceId:'qa-fixture',projectId:'p',recordingId:'r',contentHash:'source-hash',sourceMode:'native',segments:[{segmentId:'seg',startMs:0,endMs:500,text:'Chef ตรวจหน้าเว็บ'}]};
 const mid=addSource(domain,src,{title:'QA meeting'}),sourceId=domain.meetings[0].sourceId,rid=saveReview(domain,{sourceId,segments:src.segments,reviewHash:'review-hash'});
 addBatch(domain,mid,{draftBatchId:'batch-qa',reviewRevisionId:rid,reviewHash:'review-hash',sourceHash:'source-hash',items:[{proposalId:'p1',kind:'task',title:'ตรวจหน้าเว็บ',evidence:[{segmentId:'seg',startMs:0,endMs:500,quote:'ตรวจหน้าเว็บ',reviewRevisionId:rid}]}]});
 commitBatch(domain,'batch-qa',[{proposalId:'p1',mode:'create',title:'ตรวจหน้าเว็บ',responsibleId:domain.members[0].id,week:'2026-09-28',priority:'must'}]);
 const backup={schemaVersion:2,appId:'dashboard:354c0a91-d04c-431c-9fe5-06bc3f703be1',campaignWorkspace:ws,meetingTaskManager:domain};
 await assert.rejects(run(b,c=>importPreview(c,b,{backup})),/transcript/);
 const report=await run(b,c=>importPreview(c,b,{backup,includeTranscript:true,source_namespace:randomUUID()}));assert.equal((await run(b,c=>snapshot(c,b))).campaigns.length,0);
 const imported=await run(b,c=>importCommit(c,b,report.id,{backup_sha256:report.backup_sha256}));assert.equal(imported.workspace.meetingTaskManager.tasks.length,6);assert.equal(imported.workspace.meetingTaskManager.members.length,4);assert.equal(imported.workspace.meetingTaskManager.weeks[0].entries.at(-1).priority,'must');
 const after=imported.workspace;assert.equal(measure(after.campaignWorkspace.campaigns[0]).spend,123);assert.equal(after.campaignWorkspace.campaigns[0].tasks.length,1);assert.doesNotThrow(()=>validateState(after.meetingTaskManager));
 assert.equal((await run(b,c=>importCommit(c,b,report.id,{backup_sha256:report.backup_sha256}))).alreadyCommitted,true);
 const d=after.meetingTaskManager;saveTask(d,{id:d.tasks[0].id,version:d.tasks[0].version,description:'เติมภายหลัง'});
 const saved=await run(b,c=>saveLegacy(c,b,{version:after.version,campaignWorkspace:after.campaignWorkspace,meetingTaskManager:d}));
 assert.equal(saved.campaignWorkspace.campaigns[0].tasks.length,1);assert.equal(saved.meetingTaskManager.tasks.find(t=>t.id===d.tasks[0].id).description,'เติมภายหลัง');assert.equal(saved.meetingTaskManager.receipts.length,1);assert.deepEqual(saved.meetingTaskManager.sources,domain.sources);
 await assert.rejects(run(b,c=>saveLegacy(c,b,{version:after.version,meetingTaskManager:d})),e=>e.status===409);
 const bad=structuredClone(saved.meetingTaskManager);bad.sources[0].segments[0].text='overwrite';await assert.rejects(run(b,c=>saveLegacy(c,b,{version:saved.version,meetingTaskManager:bad})),/revision/);
 assert.equal((await run(b,c=>readLegacy(c,b))).version,saved.version);
 const replay=await run(b,c=>saveLegacy(c,b,{version:saved.version,campaignWorkspace:saved.campaignWorkspace,meetingTaskManager:saved.meetingTaskManager}));assert.equal(replay.campaignWorkspace.campaigns[0].tasks.length,1);
});
test('canonical hashes ignore object key order after JSONB storage',()=>assert.equal(hash({b:1,a:{y:3,x:2}}),hash({a:{x:2,y:3},b:1})));
