import test from 'node:test';
import assert from 'node:assert/strict';
import {periodFor,midnight,goalProgress,overview,validateSummarySelection} from '../../web/src/content/business/model.mjs';
const asOf='2026-09-30T05:00:00.000Z';
function fixture(){return {business:{timezone:'Asia/Bangkok'},campaigns:[],content_items:[],publications:[],goals:[],tasks:[],channel_accounts:[{id:'a',display_name:'QA'}],metric_series:[{id:'s',channel_account_id:'a',metric_code:'followers_total',freshness_hours:48}],goal_series:[{goal_id:'g',series_id:'s'}],metric_observations:[{id:'b',series_id:'s',is_current:true,effective_at:midnight('2026-09-28'),value:1000,coverage:'complete'},{id:'l',series_id:'s',is_current:true,effective_at:asOf,value:1320,coverage:'complete'}]};}
const goal={id:'g',name:'ผู้ติดตามใหม่',metric_code:'followers_net',period_start:'2026-09-28',period_end_exclusive:'2026-10-05',period_kind:'weekly',target_value:500};
test('Bangkok boundaries include Monday and calendar month',()=>{assert.deepEqual(periodFor('2026-10-04'),{start:'2026-09-28',end:'2026-10-05'});assert.deepEqual(periodFor('2026-12-31','monthly'),{start:'2026-12-01',end:'2027-01-01'});assert.equal(midnight('2026-09-28'),'2026-09-27T17:00:00.000Z');assert.throws(()=>periodFor('2026-02-31'));});
test('net followers 320/500 differs from total stock 1320',()=>{const p=goalProgress(goal,fixture(),asOf);assert.equal(p.actual,320);assert.equal(p.stock,1320);assert.equal(p.percent,64);assert.equal(p.remaining,180);assert.equal(p.quality,'complete');});
test('missing baseline is unknown and cannot masquerade as zero',()=>{const d=fixture();d.metric_observations.shift();assert.equal(goalProgress(goal,d,asOf).actual,null);d.metric_observations=[];assert.equal(goalProgress(goal,d,asOf).quality,'missing');});
test('confirmed zero, negative and above-target deltas preserve meaning',()=>{const d=fixture();d.metric_observations[1].value=1000;assert.equal(goalProgress(goal,d,asOf).actual,0);d.metric_observations[1].value=900;assert.equal(goalProgress(goal,d,asOf).actual,-100);assert.equal(goalProgress(goal,d,asOf).barPercent,0);d.metric_observations[1].value=1600;assert.equal(goalProgress(goal,d,asOf).percent,120);assert.equal(goalProgress(goal,d,asOf).barPercent,100);});
test('stale and misaligned account snapshots never become a complete scope',()=>{const d=fixture();d.metric_observations[1].effective_at='2026-09-27T17:01:00Z';assert.equal(goalProgress(goal,d,asOf).quality,'stale');const e=fixture();e.metric_series.push({...e.metric_series[0],id:'s2'});e.goal_series.push({goal_id:'g',series_id:'s2'});e.metric_observations.push(...e.metric_observations.map(o=>({...o,id:o.id+'2',series_id:'s2',effective_at:o.id==='l'?'2026-09-30T04:00:00Z':o.effective_at})));assert.equal(goalProgress(goal,e,asOf).quality,'partial');});
test('one monthly content item has three scheduled channel publications',()=>{const d=fixture();d.content_items=[{id:'c',planning_month:'2026-09-01'}];d.publications=Array.from({length:3},(_,i)=>({id:String(i),content_item_id:'c',status:'scheduled',scheduled_at:'2026-10-01T05:00:00Z'}));d.publications.push({id:'old',status:'scheduled',scheduled_at:'2026-09-29T00:00:00Z'});const v=overview(d,{date:'2026-09-30',asOf});assert.equal(v.counts.scheduled,3);assert.equal(v.counts.scheduledContents,1);assert.equal(v.counts.contentMonth,1);assert.equal(v.overdue.length,1);assert.equal(overview(d,{date:'2026-10-12',asOf}).counts.scheduled,0);});
test('lifecycle is explicit, archived excluded and unknown not treated as queued',()=>{const d=fixture();d.campaigns=[{lifecycle:'active'},{lifecycle:'queued'},{lifecycle:'unconfirmed'},{lifecycle:'active',archived_at:asOf}];assert.deepEqual(Object.fromEntries(Object.entries(overview(d,{asOf}).counts).slice(0,3)),{active:1,queued:1,unconfirmed:1});});
test('AI can select only evidence-backed facts',()=>{const facts=[{id:'x',text:'known'}];assert.deepEqual(validateSummarySelection({factIds:['x']},facts),facts);assert.throws(()=>validateSummarySelection({factIds:['invented']},facts));assert.throws(()=>validateSummarySelection({factIds:['x','x']},facts));});
